### ISSUE TITLE
流程图转换json文件，缺少output节点

### ISSUE THREAD

**Issue by majinshan** [baidu/unit-dmkit#10]
做了一个最简单的流程如下，但用run.py转换后，为什么不能输出第一个节点信息(hello)？
![xnip2018-08-13_10-57-21](https://user-images.githubusercontent.com/4122134/44010895-c4239cec-9ee7-11e8-8b37-c5f35b955d57.jpg)

xml:
-------------------------
<root>
<mxCell id="0"/>
<mxCell id="1" parent="0"/>
<mxCell id="6" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;jettySize=auto;orthogonalLoop=1;" edge="1" parent="1" source="2" target="3">
<mxGeometry relative="1" as="geometry"/>
</mxCell>
<mxCell id="2" value="BOT:hello" style="rounded=1;whiteSpace=wrap;html=1;" vertex="1" parent="1">
<mxGeometry x="280" y="90" width="120" height="60" as="geometry"/>
</mxCell>
<mxCell id="7" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;jettySize=auto;orthogonalLoop=1;" edge="1" parent="1" source="3" target="4">
<mxGeometry relative="1" as="geometry"/>
</mxCell>
<mxCell id="3" value="INTENT:greeting" style="ellipse;whiteSpace=wrap;html=1;rounded=1;" vertex="1" parent="1">
<mxGeometry x="280" y="220" width="120" height="80" as="geometry"/>
</mxCell>
<mxCell id="4" value="BOT:bye" style="rounded=1;whiteSpace=wrap;html=1;" vertex="1" parent="1">
<mxGeometry x="280" y="370" width="120" height="60" as="geometry"/>
</mxCell>
<mxCell id="5" value="" style="endArrow=classic;html=1;entryX=0.5;entryY=0;" edge="1" parent="1" target="2">
<mxGeometry width="50" height="50" relative="1" as="geometry">
<mxPoint x="340" y="40" as="sourcePoint"/>
<mxPoint x="310" y="90" as="targetPoint"/>
</mxGeometry>
</mxCell>
</root>

转换后的json:

[
  {
    output: [
    ┆ {
    ┆   ┆assertion┆: [],
    ┆   ┆result┆: [
    ┆   ┆ {
    ┆   ┆   ┆type┆: ┆tts┆,
    ┆   ┆   ┆value┆: ┆bye┆
    ┆   ┆ }
    ┆   ],
    ┆   ┆session┆: {
    ┆   ┆ ┆context┆: {},
    ┆   ┆ ┆state┆: ┆002┆
    ┆   }
    ┆ }
    ],
    params: [],
    trigger: {
    ┆ ┆intent┆: ┆greeting┆,
    ┆ ┆slots┆: [],
    ┆ ┆state┆: ┆001┆
    }
  }
]

**Comment by majinshan** [comment]
xml文件：
[sample.txt](https://github.com/baidu/unit-dmkit/files/2281670/sample.txt)

**Comment by jiyoushengbd** [comment]
每个BOT回复节点需要有一个INTENT意图节点作为触发条件，否则无法被触发。例子中hello节点无对应的意图节点触发，因此无法生成对应的配置。

**Comment by majinshan** [comment]
多谢！
