### ISSUE TITLE
mac 编辑出错

### ISSUE THREAD

**Issue by rhyspang** [baidu/unit-dmkit#11]
系统: 
MACOS HIGH SIERRA 10.13.6

错误信息：

In file included from /Users/rhys/Workspace/personal/unit-dmkit/brpc/src/butil/mac/scoped_mach_port.cc:5:
In file included from /Users/rhys/Workspace/personal/unit-dmkit/brpc/src/butil/logging.h:30:
In file included from /Users/rhys/Workspace/personal/unit-dmkit/brpc/src/butil/atomicops.h:147:
/Users/rhys/Workspace/personal/unit-dmkit/brpc/src/butil/atomicops_internals_mac.h:137:10: warning: 'OSAtomicAdd64Barrier' is
      deprecated: first deprecated in macOS 10.12 - Use std::atomic_fetch_add() from <atomic> instead [-Wdeprecated-declarations]
  return OSAtomicAdd64Barrier(increment,
         ^
/usr/include/libkern/OSAtomicDeprecated.h:247:9: note: 'OSAtomicAdd64Barrier' has been explicitly marked deprecated here
int64_t OSAtomicAdd64Barrier( int64_t __theAmount,
        ^
In file included from /Users/rhys/Workspace/personal/unit-dmkit/brpc/src/butil/mac/scoped_mach_port.cc:5:
In file included from /Users/rhys/Workspace/personal/unit-dmkit/brpc/src/butil/logging.h:30:
In file included from /Users/rhys/Workspace/personal/unit-dmkit/brpc/src/butil/atomicops.h:147:
/Users/rhys/Workspace/personal/unit-dmkit/brpc/src/butil/atomicops_internals_mac.h:146:9: warning: 'OSAtomicCompareAndSwap64Barrier' is
      deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong() from <atomic> instead
      [-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap64Barrier(
        ^
/usr/include/libkern/OSAtomicDeprecated.h:645:9: note: 'OSAtomicCompareAndSwap64Barrier' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap64Barrier( int64_t __oldValue, int64_t __newValue,
        ^
11 warnings generated.
11 warnings generated.
[ 48%] Built target BUTIL_LIB
make: *** [all] Error 2

**Comment by jiyoushengbd** [comment]
最新的BRPC在MAC上编译不过，2ae7f04ce513c6aee27545df49d5439a98ae3a3f版本测试可以编译过，建议先使用该版本。（已更新deps.sh脚本，重新执行即可）
