### ISSUE TITLE
sh deps.sh mac报错

### ISSUE THREAD

**Issue by leshphonc** [baidu/unit-dmkit#112]
下载后执行sh deps.sh mac就会报错

报错内容如下，
In file included from /Users/cc/obito/robot/unit-dmkit/brpc/src/brpc/esp_message.cpp:18:
/Users/cc/obito/robot/unit-dmkit/brpc/src/brpc/esp_message.h:37:27: error: base class has incomplete type
class EspMessage : public ::google::protobuf::Message {
                   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/google/protobuf/arena.h:76:7: note: forward declaration of 'google::protobuf::Message'
class Message;  // defined in message.h
      ^
/Users/cc/obito/robot/unit-dmkit/brpc/src/brpc/esp_message.cpp:24:10: fatal error: 'google/protobuf/wire_format_lite_inl.h' file not found
#include <google/protobuf/wire_format_lite_inl.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [src/CMakeFiles/OBJ_LIB.dir/brpc/esp_message.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....



在运行的最后还有一段这个
11 warnings generated.
11 warnings generated.
11 warnings generated.
11 warnings generated.
11 warnings generated.
11 warnings generated.
11 warnings generated.
make[1]: *** [src/CMakeFiles/OBJ_LIB.dir/all] Error 2
make: *** [all] Error 2

请问这是编译成功了？如果没成功怎么解决呢

**Comment by HuangLK** [comment]
可能是brpc与protobuf版本兼容性问题，可以尝试换用低版本的protobuf，以下命令仅供参考：
```
brew uninstall protobuf
brew install protobuf@3.6
brew link --force protobuf@3.6
```

**Comment by leshphonc** [comment]
按照您刚才提供的命令执行了一下，刚才的错误不报了，但是出了新的错误

[ 22%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/debug/debugger.cc.o
/Users/cc/obito/robot/unit-dmkit/brpc/_build/brpc/policy/mongo.pb.cc:197:5: error: no member named 'protobuf_brpc_2foptions_2eproto' in the global namespace
  ::protobuf_brpc_2foptions_2eproto::AddDescriptors();
  ~~^
1 error generated.
/Users/cc/obito/robot/unit-dmkit/brpc/_build/brpc/trackme.pb.cc:139:5: error: no member named 'protobuf_brpc_2foptions_2eproto' in the global namespace; did you mean 'protobuf_brpc_2ftrackme_2eproto'?
  ::protobuf_brpc_2foptions_2eproto::AddDescriptors();
  ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    protobuf_brpc_2ftrackme_2eproto
/Users/cc/obito/robot/unit-dmkit/brpc/_build/brpc/trackme.pb.cc:34:11: note: 'protobuf_brpc_2ftrackme_2eproto' declared here
namespace protobuf_brpc_2ftrackme_2eproto {
          ^
make[2]: *** [CMakeFiles/PROTO_LIB.dir/brpc/policy/mongo.pb.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 23%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/execution_queue.cpp.o
1 error generated.
/Users/cc/obito/robot/unit-dmkit/brpc/_build/brpc/streaming_rpc_meta.pb.cc:181:5: error: no member named 'protobuf_brpc_2foptions_2eproto' in the global namespace
  ::protobuf_brpc_2foptions_2eproto::AddDescriptors();
  ~~^
11 warnings generated.
make[2]: *** [CMakeFiles/PROTO_LIB.dir/brpc/trackme.pb.cc.o] Error 1


编译到70%就不动了，报错是在20%左右报错
11 warnings generated.
11 warnings generated.
11 warnings generated.
11 warnings generated.
11 warnings generated.
11 warnings generated.
11 warnings generated.
11 warnings generated.
[ 70%] Built target OBJ_LIB
make: *** [all] Error 2

**Comment by leshphonc** [comment]
问题解决了。我觉得是不是应该更新一下文档？？
我是mac全新环境安装dmkit，结果deps.sh里拉下来的brpc的tag好像是0.9.0的。根本不支持mac，查了半天issues才知道要切换tag然后在brpc的#974里提到的2行代码在mac10.15后加入了系统lib，是不是应该在文档里写一下？
typedef struct OpaqueSecTrustRef* SecACLRef;
typedef struct OpaqueSecTrustedApplicationRef* SecTrustedApplicationRef;

总结一下解决方法
git checkout 0.9.6
删除brpc/src/butil/mac/foundation_util.h中的2段代码

然后执行
sh deps.sh mac
mkdir _build && cd _build && cmake .. && make

**Comment by leshphonc** [comment]
另外protobuf3.7目前是不被支持的
brpc里写的protobuf: 2.4+

**Comment by rexyzhang11** [comment]
> 问题解决了。我觉得是不是应该更新一下文档？？
> 我是mac全新环境安装dmkit，结果deps.sh里拉下来的brpc的tag好像是0.9.0的。根本不支持mac，查了半天issues才知道要切换tag然后在brpc的#974里提到的2行代码在mac10.15后加入了系统lib，是不是应该在文档里写一下？
> typedef struct OpaqueSecTrustRef* SecACLRef;
> typedef struct OpaqueSecTrustedApplicationRef* SecTrustedApplicationRef;
> 
> 总结一下解决方法
> git checkout 0.9.6
> 删除brpc/src/butil/mac/foundation_util.h中的2段代码
> 
> 然后执行
> sh deps.sh mac
> mkdir _build && cd _build && cmake .. && make


您好，也遇到了同样的问题，小白解决不了，想请问可以再具体按顺序说一下具体中间的解决方法吗？
