### ISSUE TITLE
ubuntu18安装brpc报错

### ISSUE THREAD

**Issue by Jerry-ummit** [baidu/unit-dmkit#12]
[ 94%] Linking CXX shared library ../output/lib/libbrpc.so
CMakeFiles/BUTIL_LIB.dir/butil/third_party/dmg_fp/dtoa_wrapper.cc.o:无法识别文件: 文件被截断
collect2: error: ld returned 1 exit status
src/CMakeFiles/brpc-shared.dir/build.make:639: recipe for target 'output/lib/libbrpc.so' failed
make[2]: *** [output/lib/libbrpc.so] Error 1
CMakeFiles/Makefile2:206: recipe for target 'src/CMakeFiles/brpc-shared.dir/all' failed
make[1]: *** [src/CMakeFiles/brpc-shared.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 94%] Built target brpc-static
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jiyoushengbd** [comment]
删除产出目录重新编译即可。
https://stackoverflow.com/questions/5713894/file-not-recognized-file-truncated-gcc-error
