### ISSUE TITLE
在ubuntu上运行失败

### ISSUE THREAD

**Issue by tsingliuwin** [baidu/unit-dmkit#14]
ubuntu 版本 18
找到原因是由于realpath不存在，手动安装realpath,根据提示安装推荐的包，然后修改deps.sh文件，删除realpath行，再次运行 sh deps.sh ubuntu就成功了

**Comment by tsingliuwin** [comment]
elif [ $OS = ubuntu ]; then
    echo "Installing dependencies for Ubuntu..."
    sudo apt-get install git \
        g++ \
        make \
        libssl-dev \
        realpath \
ubuntu上安装realpath包错误

**Comment by jiyoushengbd** [comment]
更换为coreutils
