### ISSUE TITLE
发送消息出现ERROR: DM policy resolve failed错误

### ISSUE THREAD

**Issue by tsingliuwin** [baidu/unit-dmkit#15]
检查了一下是src/dialog_manager.cpp出现的问题，请问需要怎么修改？

**Comment by jiyoushengbd** [comment]
出现这个错误的原因是UNIT平台解析出意图在DM Kit中缺失该意图的policy配置。如果是使用demo场景，常见错误是products.json中bot_id未根据在UNIT平台所创建的bot id进行修改。

**Comment by tsingliuwin** [comment]
bot id应该没有问题，因为我胡乱写一些字发送过去会有响应，但是发送你好、嗨等正确的话时就会出现错误

**Comment by jiyoushengbd** [comment]
这个错误信息是因为输入query解析出的意图结合当前对话状态在DM Kit的配置中没有找到对应的policy，需要根据对话需求配置DM Kit
