### ISSUE TITLE
在ios上执行./dmkit出现错误

### ISSUE THREAD

**Issue by androidcg** [baidu/unit-dmkit#16]
localhost:_build unilife$ ./dmkit
I0907 16:06:15   775 /Users/unilife/desktop/unit-dmkit-master/src/dialog_manager.cpp:46] logid= _remote_service_manager init done
E0907 16:06:15   775 /Users/unilife/desktop/unit-dmkit-master/src/policy_manager.cpp:258] logid= Failed to parse RemoteServiceManager settings
E0907 16:06:15   775 /Users/unilife/desktop/unit-dmkit-master/src/policy_manager.cpp:122] logid= Failed to init policy dict
E0907 16:06:15   775 /Users/unilife/desktop/unit-dmkit-master/src/dialog_manager.cpp:49] logid= Failed to init _policy_manager
E0907 16:06:15   775 /Users/unilife/desktop/unit-dmkit-master/src/app_container.cpp:62] logid= failed to init application!!!
E0907 16:06:15   775 /Users/unilife/desktop/unit-dmkit-master/src/server.cpp:82] logid= Fail to init http_svc
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process

**Comment by jiyoushengbd** [comment]
配置文件conf目录是否在dmkit程序目录下？
