### ISSUE TITLE
ubuntu 18 编译出错

### ISSUE THREAD

**Issue by JiangSongBai** [baidu/unit-dmkit#17]
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/jiangsongbai/unit-dmkit/brpc/_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_39fe4/fast"
/usr/bin/make -f CMakeFiles/cmTC_39fe4.dir/build.make CMakeFiles/cmTC_39fe4.dir/build
make[1]: Entering directory '/home/jiangsongbai/unit-dmkit/brpc/_build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_39fe4.dir/CheckSymbolExists.c.o
/usr/bin/cc   -DBRPC_WITH_GLOG=0 -DGFLAGS_NS=google -DBTHREAD_USE_FAST_PTHREAD_MUTEX -D__const__= -D_GNU_SOURCE -DUSE_SYMBOLIZE -DNO_TCMALLOC -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -DBRPC_REVISION=\"2ae7f04\" -D__STRICT_ANSI__ -g  -O2 -pipe -Wall -W -fPIC -fstrict-aliasing -Wno-unused-parameter -fno-omit-frame-pointer    -o CMakeFiles/cmTC_39fe4.dir/CheckSymbolExists.c.o   -c /home/jiangsongbai/unit-dmkit/brpc/_build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_39fe4
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_39fe4.dir/link.txt --verbose=1
/usr/bin/cc  -DBRPC_WITH_GLOG=0 -DGFLAGS_NS=google -DBTHREAD_USE_FAST_PTHREAD_MUTEX -D__const__= -D_GNU_SOURCE -DUSE_SYMBOLIZE -DNO_TCMALLOC -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -DBRPC_REVISION=\"2ae7f04\" -D__STRICT_ANSI__ -g  -O2 -pipe -Wall -W -fPIC -fstrict-aliasing -Wno-unused-parameter -fno-omit-frame-pointer     -rdynamic CMakeFiles/cmTC_39fe4.dir/CheckSymbolExists.c.o  -o cmTC_39fe4 
CMakeFiles/cmTC_39fe4.dir/CheckSymbolExists.c.o: In function `main':
/home/jiangsongbai/unit-dmkit/brpc/_build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_39fe4.dir/build.make:97: recipe for target 'cmTC_39fe4' failed
make[1]: *** [cmTC_39fe4] Error 1
make[1]: Leaving directory '/home/jiangsongbai/unit-dmkit/brpc/_build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_39fe4/fast' failed
make: *** [cmTC_39fe4/fast] Error 2

File /home/jiangsongbai/unit-dmkit/brpc/_build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/jiangsongbai/unit-dmkit/brpc/_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_f9bb1/fast"
/usr/bin/make -f CMakeFiles/cmTC_f9bb1.dir/build.make CMakeFiles/cmTC_f9bb1.dir/build
make[1]: Entering directory '/home/jiangsongbai/unit-dmkit/brpc/_build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_f9bb1.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DBRPC_WITH_GLOG=0 -DGFLAGS_NS=google -DBTHREAD_USE_FAST_PTHREAD_MUTEX -D__const__= -D_GNU_SOURCE -DUSE_SYMBOLIZE -DNO_TCMALLOC -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -DBRPC_REVISION=\"2ae7f04\" -D__STRICT_ANSI__ -g  -O2 -pipe -Wall -W -fPIC -fstrict-aliasing -Wno-unused-parameter -fno-omit-frame-pointer -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_f9bb1.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_f9bb1
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f9bb1.dir/link.txt --verbose=1
/usr/bin/cc  -DBRPC_WITH_GLOG=0 -DGFLAGS_NS=google -DBTHREAD_USE_FAST_PTHREAD_MUTEX -D__const__= -D_GNU_SOURCE -DUSE_SYMBOLIZE -DNO_TCMALLOC -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -DBRPC_REVISION=\"2ae7f04\" -D__STRICT_ANSI__ -g  -O2 -pipe -Wall -W -fPIC -fstrict-aliasing -Wno-unused-parameter -fno-omit-frame-pointer -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_f9bb1.dir/CheckFunctionExists.c.o  -o cmTC_f9bb1 -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_f9bb1.dir/build.make:97: recipe for target 'cmTC_f9bb1' failed
make[1]: *** [cmTC_f9bb1] Error 1
make[1]: Leaving directory '/home/jiangsongbai/unit-dmkit/brpc/_build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_f9bb1/fast' failed
make: *** [cmTC_f9bb1/fast] Error 2

**Comment by jiyoushengbd** [comment]
检查一下是否安装了pthread？

**Comment by grayfantasy** [comment]
@JiangSongBai ，你好，我碰到了同样的问题，请问你如何解决的。
