### ISSUE TITLE
[建议] git clone的时候，增加 --depth 1 

### ISSUE THREAD

**Issue by icedfish** [baidu/unit-dmkit#20]
https://github.com/baidu/unit-dmkit/blob/a62d80f091e408c95062283aa4bf93c87034ba0b/deps.sh#L50

git clone的时候，增加 --depth 1 吧，可以提升不少clone速度。 反正只要最新版就可以用于build了。

**Comment by lyc-baidu** [comment]
建议收到，下一版本考虑加上。
