### ISSUE TITLE
关于流程图和slot值的一些问题

### ISSUE THREAD

**Issue by CrazyTianC** [baidu/unit-dmkit#21]
1.使用可视化draw.io绘制流程图的时候，会因为字体等问题导致转化失败。
我直接使用默认字体输入的时候，发现转化不成功（PARAMS处），后来我把demo里的格式刷过去，就可以了。

2.想问一下如何获取全部NLU解析的slot值。
例如time词槽为今天，但是通过func_val传递{%time%}值的时候，只有‘2019-02-18’，不知道如何在dmkit中获取全量的解析值（例如置信度，词槽值）。

3.不知道user_function是否支持python。
因为不懂C++，所以现在是通过python写接口然后调用的方式，不知道有没有更好的办法。

4.调用service_http_get时编码总是不对，service_http_post就没有问题。

**Comment by CrazyTianC** [comment]
第4个问题解决了。
原因是：本身是unicode编码，却被当作GBK系列来解码，结果导致乱码。
解决办法：text.encode('raw_unicode_escape').decode()

**Comment by coneycode** [comment]
问下第一个问题哈：转化不成功 具体是什么现象麻烦说下，期望结果是什么？真实结果是什么？

**Comment by CrazyTianC** [comment]
[fix1.xml.zip](https://github.com/baidu/unit-dmkit/files/2908943/fix1.xml.zip)
具体是params无法识别。以上是用draw.io导出的xml文件，使用draw.io打开和转化之后的内容在params处不相符。我也不知道当时为啥会写出来这种格式。。
