### ISSUE TITLE
编译DM kit出错，anaconda licurl.so

### ISSUE THREAD

**Issue by XufengXufengXufeng** [baidu/unit-dmkit#22]
使用 'sh deps.sh ubuntu' 下载并编译brpc后报错。手动编译brpc，使用echo_c++server的例子也没问题。但是当编译DM kit时候出以下报错，求解。

/home/namename/anaconda3/lib/libcurl.so：对‘SSLv2_client_method’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/dmkit.dir/build.make:454: recipe for target 'dmkit' failed
make[2]: *** [dmkit] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dmkit.dir/all' failed
make[1]: *** [CMakeFiles/dmkit.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

安装环境为：
protoc：3.5.1
protobuf:3.5.1
ubuntu:16.04
anaconda:4.5.11

**Comment by lyc-baidu** [comment]
确认一下libcurl版本不低于7.32

**Comment by chl916185** [comment]
[ 81%] Building CXX object CMakeFiles/dmkit.dir/src/user_function/shared.cpp.o
[ 87%] Building CXX object CMakeFiles/dmkit.dir/src/user_function/demo.cpp.o
[ 93%] Building CXX object CMakeFiles/dmkit.dir/http.pb.cc.o
[100%] Linking CXX executable dmkit
/usr/bin/ld: warning: libssl.so.1.1, needed by /home/chl/anaconda2/lib/libcurl.so, may conflict with libssl.so.1.0.0
/usr/bin/ld: warning: libcrypto.so.1.1, needed by /home/chl/anaconda2/lib/libcurl.so, may conflict with libcrypto.so.1.0.0
/home/chl/anaconda2/lib/libcom_err.so.3: undefined reference to `k5_os_mutex_destroy@krb5support_0_MIT'
/home/chl/anaconda2/lib/libcom_err.so.3: undefined reference to `k5_os_mutex_lock@krb5support_0_MIT'
/home/chl/anaconda2/lib/libcom_err.so.3: undefined reference to `k5_once@krb5support_0_MIT'
/home/chl/anaconda2/lib/libcom_err.so.3: undefined reference to `k5_os_mutex_unlock@krb5support_0_MIT'
collect2: error: ld returned 1 exit status
CMakeFiles/dmkit.dir/build.make:454: recipe for target 'dmkit' failed
make[2]: *** [dmkit] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dmkit.dir/all' failed
make[1]: *** [CMakeFiles/dmkit.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
我遇到了同样的错误，我的libcurl版本如下：curl --version
curl 7.63.0 (x86_64-conda_cos6-linux-gnu) libcurl/7.63.0 OpenSSL/1.1.1b zlib/1.2.11 libssh2/1.8.0
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 
@lyc-baidu @nwind 
请指教下，非常感谢

**Comment by lyc-baidu** [comment]
看起来像是libcurl.so没有链接libkrb5support.so，可以先确认一下

**Comment by chl916185** [comment]
chl@chl:~/work_files/unit-dmkit/_build$ ldd /home/chl/anaconda2/lib/libcurl.so
	linux-vdso.so.1 =>  (0x00007fff3cdcf000)
	/usr/lib/libtcmalloc_minimal.so.4 (0x00007f3afd562000)
	libssh2.so.1 => /home/chl/anaconda2/lib/./libssh2.so.1 (0x00007f3afd91a000)
	libssl.so.1.1 => /home/chl/anaconda2/lib/./libssl.so.1.1 (0x00007f3afd884000)
	libcrypto.so.1.1 => /home/chl/anaconda2/lib/./libcrypto.so.1.1 (0x00007f3afd26a000)
	libgssapi_krb5.so.2 => /home/chl/anaconda2/lib/./libgssapi_krb5.so.2 (0x00007f3afd834000)
	libkrb5.so.3 => /home/chl/anaconda2/lib/./libkrb5.so.3 (0x00007f3afd18e000)
	libk5crypto.so.3 => /home/chl/anaconda2/lib/./libk5crypto.so.3 (0x00007f3afd814000)
	libcom_err.so.3 => /home/chl/anaconda2/lib/./libcom_err.so.3 (0x00007f3afd80e000)
	libz.so.1 => /home/chl/anaconda2/lib/./libz.so.1 (0x00007f3afcf77000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3afcd6f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3afcb52000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3afc788000)
	libstdc++.so.6 => /home/chl/anaconda2/lib/./libstdc++.so.6 (0x00007f3afc647000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3afc33e000)
	libgcc_s.so.1 => /home/chl/anaconda2/lib/./libgcc_s.so.1 (0x00007f3afc329000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3afc125000)
	libkrb5support.so.0 => /home/chl/anaconda2/lib/././libkrb5support.so.0 (0x00007f3afc116000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f3afbefb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3afd7af000)
chl@chl:~/work_files/unit-dmkit/_build$ 

@lyc-baidu 
麻烦您看看，这是链接上了吗

**Comment by lyc-baidu** [comment]
看起来是环境的问题，尝试使用系统自带库进行编译
