### ISSUE TITLE
fail to call unit bot api

### ISSUE THREAD

**Issue by jeffrey0617** [baidu/unit-dmkit#25]
在腾讯服务器上调用dmkit，报错，说

service_unit_bot=remote:103.235.46.47:443|tm:400|ret:-1 ret={"error_code":-1,"error_msg":"Failed to call unit bot api"} tm=400.544970

请问这是什么问题

**Comment by lyc-baidu** [comment]
是否超时所致？可参考[https://github.com/baidu/unit-dmkit/blob/master/docs/faq.md#%E8%BF%94%E5%9B%9E%E9%94%99%E8%AF%AF%E4%BF%A1%E6%81%AF-failed-to-call-unit-bot-api](url)
