### ISSUE TITLE
日志同步

### ISSUE THREAD

**Issue by xyjiao** [baidu/unit-dmkit#26]
请问dmkit的日志如何同步？

**Comment by lyc-baidu** [comment]
可以详细描述一下问题吗？谢谢

**Comment by xyjiao** [comment]
dmkit在启动后会输出运行日志，如：

I0228 15:06:18.646372 22239 /download/test/unit-dmkit/brpc/src/brpc/detail/naming_service_thread.cpp:185] brpc::policy::DomainNamingService("127.0.0.1:5000"): added 1
I0228 15:06:18.646822 22236 /download/test/unit-dmkit/src/dialog_manager.cpp:46] logid= _remote_service_manager init done
I0228 15:06:18.647038 22236 /download/test/unit-dmkit/src/policy_manager.cpp:345] logid= Loading policies for product: default
I0228 15:06:18.647062 22236 download/test/unit-dmkit/src/policy_manager.cpp:367] logid= Loading policies for domain 4052 from conf/app/demo/cellular_data.json
I0228 15:06:40.546213 22242 /download/test/unit-dmkit/src/dialog_manager.cpp:64] logid= received request: {"bot_session":"{\"bot_id\":\"20660\",\"bot_views\":{\"bernard_res\":[{\"action_list\":[{\"action_id\":\"fail_action\",\"confidence\":0.0,\"custom_reply\":\"\",\"refine_detai.....
I0228 15:06:40.547893 22242 /download/test/unit-dmkit/src/dialog_manager.cpp:297] logid=dmkit_5325252 {"bot_session":"{\"bot_id\":\"20660\",\"bot_views\":{\"bernard_res\":[{\"action_list\":[{\"action_id\":\"fail_action\",\"confidence\":0.0,\"custom_reply\":\"\",\"refine_detail\":{\"clarify_reason\":\"\",\"interact\":\"\",\"option_list\":[]},\"say\":\"请您换个问法\",\"type\":\"failure\"}],\"msg\":\"ok\",\"pre_nlu_outs\":[{\"otags_basic\":[],\"otags_wpcomp\":[],\"polarity\":{\"label\":\"1\",\"pval\":0.998},\"tokens_basic\":[{\"buffer\":\"你好\",\"length\":4,\"norm_degree\":0.0,\"offset\":0,\"type\":19,\"weight\":1.0}],\"tokens_wpcomp\":[{\"buffer\":\"你好\",\"length\":4,\"norm_degree\":0.0,\"offset\":0,\"type\":19,\"weight\":1.0}]}],\"qu_res\":{\"candidates\":[],\"lexical_analysis\":[{\"basic_word\":[\"你好\"],\"etypes\":[],\"term\":\"你好\",\"type\":\"19\",\"weight\":1.0}],\"qu_res_chosen\":\"\",\"raw_query\":\"你好\",\"sentiment_analysis\":{\"label\":\"1\",\"pval\":0.998},\"status\":0,\"timestamp\":0},\
I0228 15:06:41.449577 22242 /download/test/unit-dmkit/src/policy_manager.cpp:225] logid=dmkit_5325252 Resolving policy output for domain [20660]
I0228 15:06:41.449591 22242 /download/test/unit-dmkit/src/policy_manager.cpp:625] logid=dmkit_5325252 resolving parameter [answer_list]
I0228 15:06:41.449645 22242 /download/test/unit-dmkit/src/policy_manager.cpp:744] logid=dmkit_5325252 Parameter value [答案001]
I0228 15:06:41.449656 22242 /download/test/unit-dmkit/src/policy_manager.cpp:625] logid=dmkit_5325252 resolving parameter [faq_answer]
I0228 15:06:41.449715 22242 /download/test/unit-dmkit/src/policy_manager.cpp:744] logid=dmkit_5325252 Parameter value [答案001]
I0228 15:06:41.449729 22242 /download/test/unit-dmkit/src/policy_manager.cpp:751] logid=dmkit_5325252 Candidate output size [1]
I0228 15:06:41.449739 22242 /download/test/unit-dmkit/src/policy_manager.cpp:830] selected output at index [0]

请问如何才能将这些日志，保存到文件，数据库，或是收集到日志系统，支持配置方式实现吗，目前这样的功能吗？

**Comment by lyc-baidu** [comment]
保存到文件的话，可以使用nohup后台启动，也可以在启动时添加2>重定向
