### ISSUE TITLE
槽位值可以是kw特征词吗？

### ISSUE THREAD

**Issue by Yecgaa1** [baidu/unit-dmkit#28]
在：
椭圆，用户节点，椭圆中存放的是用户的意图，以及槽位值（可选），内部语言格式为：
INTENT: intent_xxx
SLOT:user_a,user_b
的SLOT中
是否支持kw类特征词

**Comment by coneycode** [comment]
UNIT云端接口中并不返回kw类特征值，因此无法支持~
