### ISSUE TITLE
如果在draw.io图中粘贴文字，导出的xml中会带有html转义后的标签，导致转json失败

### ISSUE THREAD

**Issue by jiangshilin** [baidu/unit-dmkit#29]
如果从draw.io图形或网页中复制粘贴，就会出现这种问题。例如，意图`INTENT:WELCOME`在xml中会变为`&lt;span&gt;INTENT:WELCOME&lt;/span&gt;`
DMKit可以考虑在转json时做一下标签过滤。

**Comment by lyc-baidu** [comment]
是把draw.io图中的文字粘贴到draw.io里面吗

**Comment by jiangshilin** [comment]
多种情况都会这样：
1.把draw.io图中的文字粘贴到draw.io里面

**Comment by lyc-baidu** [comment]
使用的浏览器是？也可以更换浏览器重新尝试一下

**Comment by jiangshilin** [comment]
标准最新版chrome
