### ISSUE TITLE
PARAM参数表达式中是否支持数学运算？

### ISSUE THREAD

**Issue by jiangshilin** [baidu/unit-dmkit#33]
我想实现一个需求：如果用户不回答，机器人回复：
第一次：喂，在吗？
第二次：喂，您能听到我的说话吗？
第三次：喂，在吗？我这边听不见您的声音，先挂了，再见。
通过保存在session中计数器累加，判断不同的output输出。

**Comment by lyc-baidu** [comment]
目前只支持比较大小、是否在列表内、列表是否为空等判定，暂不支持累加功能
