### ISSUE TITLE
在dmit的提供的”调整银行卡额度“例子中，意图”INTENT: INTENT_ADJUST_QUOTA“根据词槽的匹配值，给出不同的答复，这个在UNIT里面如何配置

### ISSUE THREAD

**Issue by grayfantasy** [baidu/unit-dmkit#35]
请教，在dmit的提供的”调整银行卡额度“例子中，意图”INTENT: INTENT_ADJUST_QUOTA“根据词槽的匹配值，给出不同的答复，这个在UNIT里面如何配置

**Comment by lyc-baidu** [comment]
词槽值在UNIT里面的“训练数据”中的“词槽管理”进行配置，答复无需在UNIT页面配置
