### ISSUE TITLE
开始时需要怎么部署新项目

### ISSUE THREAD

**Issue by Yecgaa1** [baidu/unit-dmkit#36]
是先要在ai.baidu.com上部署所有的要添加的意图和词槽再编辑这个对话流程
亦或是
在第一次测试项目时会自动同步词槽和意图

**Comment by lyc-baidu** [comment]
先在ai.baidu.com上部署所有的要添加的意图和词槽，再编辑对话流程，具体可以参考视频课程：http://abcinstitute.baidu.com/pages/index.html#/courseInfo/14819
