### ISSUE TITLE
在docker镜像的ubuntu系统上运行dmkit测试程序，程序报错，详细错误见图。

### ISSUE THREAD

**Issue by kongkongthu** [baidu/unit-dmkit#41]
![image](https://user-images.githubusercontent.com/32895120/54969286-85dde780-4fb8-11e9-97bc-a6b66294b2cf.png)
这是用咱们的dockerfile文件做的一个docker镜像系统，按照说明的流程配置好了unit系统和dmkit，运行bot_emulator.py报了上面的错误。不知道哪里出了问题，求解。

**Comment by lyc-baidu** [comment]
可以先在UNIT云端测试是否有话术回复。如果没有回复的话，检查一下UNIT配置是否全部完成。
