### ISSUE TITLE
DM policy resolve failed

### ISSUE THREAD

**Issue by Yecgaa1** [baidu/unit-dmkit#42]
多次精简检查文档，仍没能解决问题
dmkit日志：

I0328 10:43:47.109226 19708 /home/xutongxin/unit-dmkit/src/qu_result.cpp:77] logid=dmkit_326366 domain:42634 intent:INTENT_DREW slots: {}
I0328 10:43:47.109298 19708 /home/xutongxin/unit-dmkit/src/app_container.cpp:97] logid=dmkit_326366 Application run cost(ms): 474.53
N0328 10:43:47.109322 19708 /home/xutongxin/unit-dmkit/src/app_container.cpp:99] logid=dmkit_326366 req={"log_id": "326366", "version": "2.0", "request": {"user_id": "9801", "query_info": {"source": "ASR", "type": "TEXT", "asr_candidates": []}, "bernard_level": 1, "updates": "", "query": "\u6d41\u7a0b\u56fe", "client_session": "{\"client_results\":\"\", \"candidate_options\":[]}"}, "bot_session": "", "bot_id": "42634"} service_token_auth=remote:183.232.232.56:443|tm:77|ret:0 service_unit_bot=remote:183.232.232.56:443|tm:396|ret:0 ret={"error_code":-1,"error_msg":"DM policy resolve failed"} tm=474.530044 

_build下products.json文件:

{
    "default": {
        "42634": {
            "score": 1,
            "conf_path": "/home/xutongxin/unit-dmkit/_build/conf/app/demo/1.3.json"
        }
    }
}

bot_token已填写

input:
流程图
BOT:
ERROR: DM policy resolve failed
-----------------------------------------------------------------
input:

**Comment by Yecgaa1** [comment]
？？？？

**Comment by lyc-baidu** [comment]
参考https://github.com/baidu/unit-dmkit/blob/master/docs/faq.md#返回错误信息-dm-policy-resolve-failed 进行检查，如果均没问题，贴一下相关配置和日志

**Comment by Yecgaa1** [comment]
已经检查，不知道错误在哪里

**日志：**
I0328 10:43:47.109226 19708 /home/xutongxin/unit-dmkit/src/qu_result.cpp:77] logid=dmkit_326366 domain:42634 intent:INTENT_DREW slots: {}
I0328 10:43:47.109298 19708 /home/xutongxin/unit-dmkit/src/app_container.cpp:97] logid=dmkit_326366 Application run cost(ms): 474.53
N0328 10:43:47.109322 19708 /home/xutongxin/unit-dmkit/src/app_container.cpp:99] logid=dmkit_326366 req={"log_id": "326366", "version": "2.0", "request": {"user_id": "9801", "query_info": {"source": "ASR", "type": "TEXT", "asr_candidates": []}, "bernard_level": 1, "updates": "", "query": "\u6d41\u7a0b\u56fe", "client_session": "{"client_results":"", "candidate_options":[]}"}, "bot_session": "", "bot_id": "42634"} service_token_auth=remote:183.232.232.56:443|tm:77|ret:0 service_unit_bot=remote:183.232.232.56:443|tm:396|ret:0 ret={"error_code":-1,"error_msg":"DM policy resolve failed"} tm=474.530044

**_build下products.json文件:**

{
"default": {
"42634": {
"score": 1,
"conf_path": "/home/xutongxin/unit-dmkit/_build/conf/app/demo/1.3.json"
}
}
}

bot_token已填写

可以要求我补充词槽，但是似乎在执行流程回复时出错。
xml：
![TIM图片20190410130256](https://user-images.githubusercontent.com/38446391/55852905-5f5fa500-5b91-11e9-92ad-83d403570fb1.png)

**Comment by Yecgaa1** [comment]
即，它要求我补充必填词槽，然后就DM策略解析失败

似乎是个基础的问题，但是我们未能检查出来，感谢您的耐心解答

**Comment by lyc-baidu** [comment]
xml是否已生成json格式的配置？

**Comment by Yecgaa1** [comment]
是的，转换时没有报错

**Comment by lyc-baidu** [comment]
能否发一下json中"intent": "INTENT_DREW"对应的output配置？

**Comment by Yecgaa1** [comment]
[
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "离线将失去云端同步功能。请输入路径（可回到在线）"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "001"
        }
      }
    ], 
    "params": [], 
    "trigger": {
      "intent": "INTENT：INTENT_DREW", 
      "slots": [], 
      "state": ""
    }
  }, 
  {
    "output": [], 
    "params": [
      {
        "name": "back", 
        "type": "func_val", 
        "value": "user_back"
      }, 
      {
        "name": "localtion", 
        "type": "func_val", 
        "value": "user_localtion"
      }, 
      {
        "name": "last", 
        "type": "func_val", 
        "value": "user_last"
      }
    ], 
    "trigger": {
      "intent": "", 
      "slots": [
        "user_localtion", 
        "user_back", 
        "user_last", 
        ""
      ], 
      "state": "001"
    }
  }, 
  {
    "output": [
      {
        "assertion": [
          {
            "type": "eq", 
            "value": "{%check%},0"
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "连接失败，请检查网络"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "004"
        }
      }, 
      {
        "assertion": [
          {
            "type": "eq", 
            "value": "{%check%},1"
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "连接成功，需要打开上一次的文件吗，亦或是新建"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "003"
        }
      }
    ], 
    "params": [
      {
        "name": "check", 
        "type": "func_val", 
        "value": "1"
      }
    ], 
    "trigger": {
      "intent": "INTENT：", 
      "slots": [
        "user_last", 
        ""
      ], 
      "state": "002"
    }
  }, 
  {
    "output": [
      {
        "assertion": [
          {
            "type": "eq", 
            "value": "{%check%},0"
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "连接失败，请检查网络"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "004"
        }
      }, 
      {
        "assertion": [
          {
            "type": "eq", 
            "value": "{%check%},1"
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "连接成功，需要打开上一次的文件吗，亦或是新建"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "003"
        }
      }
    ], 
    "params": [
      {
        "name": "check", 
        "type": "func_val", 
        "value": "1"
      }
    ], 
    "trigger": {
      "intent": "INTENT：", 
      "slots": [
        "user_last", 
        ""
      ], 
      "state": ""
    }
  }, 
  {
    "output": [
      {
        "assertion": [
          {
            "type": "ne", 
            "value": "{%new%},\"\""
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "好的"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "006"
        }
      }, 
      {
        "assertion": [
          {
            "type": "ne", 
            "value": "{%last%},\"\""
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "好的"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "005"
        }
      }, 
      {
        "assertion": [
          {
            "type": "eq", 
            "value": "{%last%},\"\""
          }, 
          {
            "type": "eq", 
            "value": "{%last%},\"\""
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "好的"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "007"
        }
      }
    ], 
    "params": [
      {
        "name": "last", 
        "type": "func_val", 
        "value": "user_last"
      }, 
      {
        "name": "new", 
        "type": "func_val", 
        "value": "user_new"
      }
    ], 
    "trigger": {
      "intent": "INTENT：INTENT_DREW_", 
      "slots": [
        "user_new", 
        ""
      ], 
      "state": "003"
    }
  }
]

**Comment by lyc-baidu** [comment]
检查一下流程图中INTENT后面的冒号是否为全角，应该设置为半角冒号

**Comment by Yecgaa1** [comment]
谢谢您，您说得对

**Comment by Yecgaa1** [comment]
我还想询问一下是怎么看出来的

**Comment by Yecgaa1** [comment]
便于我们以后自己检查

**Comment by lyc-baidu** [comment]
> "intent": "INTENT：INTENT_DREW"

这部分预期应该是"intent": "INTENT_DREW"

**Comment by Yecgaa1** [comment]
令我惊讶的是，run.py没有检查出这个错误，理论上所有的固定格式的前缀（如：Bot:）这些，都不是全角

**Comment by Yecgaa1** [comment]
令我惊讶的是，run.py没有检查出这个错误，是不是理论上所有的固定格式的前缀（如：Bot:）这些，都不是全角

**Comment by lyc-baidu** [comment]
这部分应该是run.py的疏漏，后续可以加强run.py的判断

**Comment by Yecgaa1** [comment]
第一次在流程图使用string，但是似乎他不是很友好


json：
[
  {
    "output": [
      {
        "assertion": [
          {
            "type": "eq", 
            "value": "{%version%},离线"
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "离线将失去云端同步功能。请输入路径"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "001"
        }
      }, 
      {
        "assertion": [
          {
            "type": "eq", 
            "value": "{%version%},在线"
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "尝试连接至协作数据"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "002"
        }
      }
    ], 
    "params": [
      {
        "name": "version", 
        "type": "string", 
        "value": "user_version"
      }, 
      {
        "name": "version", 
        "type": "string", 
        "value": ""
      }
    ], 
    "trigger": {
      "intent": "INTENT_DREW", 
      "slots": [
        "user_version"
      ], 
      "state": ""
    }
  }, 
  {
    "output": [], 
    "params": [
      {
        "name": "back", 
        "type": "func_val", 
        "value": "user_back"
      }, 
      {
        "name": "localtion", 
        "type": "func_val", 
        "value": "user_localtion"
      }, 
      {
        "name": "last", 
        "type": "func_val", 
        "value": "user_last"
      }
    ], 
    "trigger": {
      "intent": "", 
      "slots": [
        "user_localtion", 
        "user_back", 
        "user_last", 
        ""
      ], 
      "state": "001"
    }
  }, 
  {
    "output": [
      {
        "assertion": [
          {
            "type": "eq", 
            "value": "{%check%},0"
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "连接失败，请检查网络,重试？"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "004"
        }
      }, 
      {
        "assertion": [
          {
            "type": "eq", 
            "value": "{%check%},1"
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "连接成功，需要打开上一次的文件吗，亦或是新建"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "003"
        }
      }
    ], 
    "params": [
      {
        "name": "check", 
        "type": "slot_val", 
        "value": "1"
      }
    ], 
    "trigger": {
      "intent": "", 
      "slots": [
        "user_last", 
        ""
      ], 
      "state": "002"
    }
  }, 
  {
    "output": [
      {
        "assertion": [
          {
            "type": "eq", 
            "value": "{%check%},0"
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "连接失败，请检查网络,重试？"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "004"
        }
      }, 
      {
        "assertion": [
          {
            "type": "eq", 
            "value": "{%check%},1"
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "连接成功，需要打开上一次的文件吗，亦或是新建"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "003"
        }
      }
    ], 
    "params": [
      {
        "name": "check", 
        "type": "slot_val", 
        "value": "1"
      }
    ], 
    "trigger": {
      "intent": "", 
      "slots": [
        "user_last", 
        ""
      ], 
      "state": ""
    }
  }, 
  {
    "output": [
      {
        "assertion": [
          {
            "type": "ne", 
            "value": "{%new%},\"\""
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "好的"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "006"
        }
      }, 
      {
        "assertion": [
          {
            "type": "ne", 
            "value": "{%last%},\"\""
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "好的"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "005"
        }
      }, 
      {
        "assertion": [
          {
            "type": "eq", 
            "value": "{%last%},\"\""
          }, 
          {
            "type": "eq", 
            "value": "{%last%},\"\""
          }
        ], 
        "result": [
          {
            "type": "tts", 
            "value": "好的"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "007"
        }
      }
    ], 
    "params": [
      {
        "name": "last", 
        "type": "func_val", 
        "value": "user_last"
      }, 
      {
        "name": "new", 
        "type": "func_val", 
        "value": "user_new"
      }
    ], 
    "trigger": {
      "intent": "INTENT_DREW_", 
      "slots": [
        "user_new", 
        ""
      ], 
      "state": "003"
    }
  }
]
