### ISSUE TITLE
dmkit怎么配置远端服务

### ISSUE THREAD

**Issue by timmy008** [baidu/unit-dmkit#44]
在conf/app/remote_services.json这个文件中。请问怎么配置自己的服务，格式是怎么样的，看你们配置好的没有看懂，请问有具体文档么
"hotel_service": {
        "naming_service_url": "http://127.0.0.1:5000",
        "load_balancer_name": "random",
        "protocol": "http",
        "client": "brpc",
        "timeout_ms": 3000,
        "retry": 1,
        "headers": {
        }
    }

**Comment by lyc-baidu** [comment]
如果需要配置UNIT远端服务，可以参考remote_services.json的unit_bot部分；
如果需要配置请求其他远端服务，使用上述配置修改对应url即可。
启动tools/mock_api_server.py，可以模拟配置中hotel_service部分对应的远端服务。

**Comment by timmy008** [comment]
请求其他远端服务，那数据格式需要怎么定义？

**Comment by lyc-baidu** [comment]
如果是HTTP GET请求的话，可以参考conf/app/demo/book_hotel.json中带service_http_get的部分，远端服务返回的结果会填充到对应的params[].name中；
如果远端服务返回的结果较复杂，可以自己实现一个user_function请求service_http_get或者service_http_post函数。

**Comment by timmy008** [comment]
service_http_post请求的参数怎么配置，在demo中只看见service_http_get的配置方法

**Comment by lyc-baidu** [comment]
service_http_post参数配置可以参考https://github.com/baidu/unit-dmkit/blob/master/docs/tutorial.md#params中变量类型列表及其说明
