### ISSUE TITLE
Unsupported action t ype satisfy

### ISSUE THREAD

**Issue by helloGH1** [baidu/unit-dmkit#45]
"sch
ema\":{\"domain_confidence\":0.0,\"intent\":\"ROAD_INFO\",\"intent_confidence\":100.0,\"slots\":[{\"begin\":0,\"confidence\":100.0,\"length\":2,\"merge_method\":\"updated\",\"name\":\"user_from\",\"normalized_
word\":\"(NERL_PLUS_LOC_ROOT)>(\u5c71\u4e1c\u7701)>\u6d4e\u5357\u5e02\",\"original_word\":\"\u6d4e\u5357\",\"session_offset\":0,\"sub_slots\":[],\"word_type\":\"\"}]},\"status\":0},\"timestamp\":\"2019-04-10 1
8:17:14.643\"}],\"session_id\":\"session-1554891429413-3050988504-8013-14\"}", "bot_id": "45925"} service_unit_bot=remote:123.125.112.144:443|tm:430|ret:0 ret={"error_code":-1,"error_msg":"Unsupported action t
ype satisfy"} tm=433.640570

**Comment by coneycode** [comment]
使用DM Kit需要将UNIT平台中【技能设置->高级设置】中【对话回应设置】一项设置为『使用DM Kit配置』。设置该选项之后，UNIT云端使用DM Kit支持的数据协议。如设置为『在UNIT平台上配置』, DM Kit无法识别UNIT云端数据协议，将返回错误Unsupported action type satisfy。
