### ISSUE TITLE
按照md文件配置之后 一直返回282000

### ISSUE THREAD

**Issue by 690115879** [baidu/unit-dmkit#46]
N0412 14:27:35.120452 19280 /home/cxd/unit-dmkit/src/app_container.cpp:99] logid=dmkit_351720 req={"bot_id": "S16244", "request": {"client_session": "{\"client_results\":\"\", \"candidate_options\":[]}", "bernard_level": 1, "query": "hi", "query_info": {"type": "TEXT", "source": "ASR", "asr_candidates": []}, "user_id": "63915", "updates": ""}, "version": "2.0", "bot_session": "", "log_id": "351720"} service_unit_bot=remote:153.37.235.92:443|tm:237|ret:0 ret={"error_code":282000,"error_msg":"Internal error"} tm=237.830668

**Comment by coneycode** [comment]
S16244是机器人的ID吧？DMKit是在技能层面应用的。

**Comment by 690115879** [comment]
> S16244是机器人的ID吧？DMKit是在技能层面应用的。
bot_id难道不是要填机器人的id吗

**Comment by 690115879** [comment]
bot_tokens.json
