### ISSUE TITLE
在流程图使用string，但是似乎他不是很友好

### ISSUE THREAD

**Issue by Yecgaa1** [baidu/unit-dmkit#47]
报错为DM 策略解析失败
![捕获](https://user-images.githubusercontent.com/38446391/56102262-838aff80-5f5e-11e9-96fe-708d99bb2136.PNG)

**Comment by coneycode** [comment]
请贴下具体的详细错误日志哈~

**Comment by Yecgaa1** [comment]
I0416 12:06:00.278521  2980 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:451] logid=dmkit_257236 intent [INTENT_DREW] candidate count [1]
I0416 12:06:00.278542  2980 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:232] logid=dmkit_257236 Resolving policy output for domain [42634]
I0416 12:06:00.278594  2980 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:577] logid=dmkit_257236 resolving parameter [version]
I0416 12:06:00.278648  2980 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:696] logid=dmkit_257236 Parameter value [user_version]
I0416 12:06:00.278662  2980 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:577] logid=dmkit_257236 resolving parameter [version]
I0416 12:06:00.278672  2980 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:696] logid=dmkit_257236 Parameter value []
I0416 12:06:00.278681  2980 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:703] logid=dmkit_257236 Candidate output size [2]
I0416 12:06:00.278696  2980 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:711] logid=dmkit_257236 evaluating assertion, type[eq] value[,离线]
I0416 12:06:00.278713  2980 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:703] logid=dmkit_257236 Candidate output size [2]
I0416 12:06:00.278728  2980 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:711] logid=dmkit_257236 evaluating assertion, type[eq] value[,在线]
I0416 12:06:00.278801  2980 /home/xutongxin/unit-dmkit/src/app_container.cpp:97] logid=dmkit_257236 Application run cost(ms): 513.89
N0416 12:06:00.278871  2980 /home/xutongxin/unit-dmkit/src/app_container.cpp:99] logid=dmkit_257236 req={"log_id": "257236", "version": "2.0", "request": {"user_id": "52219", "query_info": {"source": "ASR", "type": "TEXT", "asr_candidates": []}, "bernard_level": 1, "updates": "", "query": "\u5728\u7ebf", "client_session": "{\"client_results\":\"\", \"candidate_options\":[]}"}, "bot_session": "{\"bot_id\":\"42634\",\"bot_views\":{\"bernard_res\":[{\"action_list\":[{\"action_id\":\"intent_drew_user_version_clarify\",\"confidence\":100.0,\"custom_reply\":\"\",\"refine_detail\":{\"clarify_reason\":\"slot_absent\",\"interact\":\"ask\",\"option_list\":[{\"info\":{\"name\":\"user_version\",\"text\":\"\u7248\u672c\"},\"option\":\"user_version\"}]},\"say\":\"\u8bf7\u6f84\u6e05\u4e00\u4e0b\uff1a\u7248\u672c\",\"type\":\"clarify\"}],\"msg\":\"ok\",\"pre_nlu_outs\":[{\"otags_basic\":[],\"otags_wpcomp\":[],\"polarity\":{\"label\":\"1\",\"pval\":0.998},\"tokens_basic\":[{\"buffer\":\"\u6d41\u7a0b\",\"length\":4,\"norm_degree\":0.9500832557678224,\"offset\":0,\"type\":21,\"weight\":0.6071991920471191},{\"buffer\":\"\u56fe\",\"length\":2,\"norm_degree\":0.9105027318000792,\"offset\":4,\"type\":21,\"weight\":0.3928007781505585}],\"tokens_wpcomp\":[{\"buffer\":\"\u6d41\u7a0b\u56fe\",\"length\":6,\"norm_degree\":0.0,\"offset\":0,\"type\":21,\"weight\":1.0}]}],\"qu_res\":{\"candidates\":[{\"confidence\":100.0,\"domain_confidence\":0.0,\"extra_info\":{\"group_id\":\"1\",\"real_threshold\":\"1\",\"threshold\":\"0.6\"},\"from_who\":\"pow-slu-lev1\",\"intent\":\"INTENT_DREW\",\"intent_confidence\":100.0,\"intent_need_clarify\":false,\"match_info\":\"{\\\"group_id\\\":\\\"1\\\",\\\"id\\\":\\\"1599245\\\",\\\"informal_word\\\":\\\"\\\",\\\"match_keywords\\\":\\\" kw_n:\u6d41\u7a0b\u56fe\\\",\\\"match_pattern\\\":\\\"[D:kw_n]\\\",\\\"ori_pattern\\\":\\\"[D:kw_n]\\\",\\\"ori_slots\\\":{\\\"confidence\\\":100.0,\\\"domain_confidence\\\":0.0,\\\"extra_info\\\":{},\\\"from_who\\\":\\\"smart_qu\\\",\\\"intent\\\":\\\"INTENT_DREW\\\",\\\"intent_confidence\\\":100.0,\\\"intent_need_clarify\\\":false,\\\"match_info\\\":\\\"[D:kw_n] kw_n:\u6d41\u7a0b\u56fe\\\",\\\"slots\\\":[{\\\"begin\\\":0,\\\"confidence\\\":100.0,\\\"father_idx\\\":-1,\\\"length\\\":6,\\\"name\\\":\\\"kw_n\\\",\\\"need_clarify\\\":false,\\\"normalized_word\\\":\\\"\\\",\\\"original_word\\\":\\\"\u6d41\u7a0b\u56fe\\\",\\\"word_type\\\":\\\"\\\"}]},\\\"real_threshold\\\":1.0,\\\"threshold\\\":0.6000000238418579}\",\"slots\":[]}],\"lexical_analysis\":[{\"basic_word\":[\"\u6d41\u7a0b\"],\"etypes\":[],\"term\":\"\u6d41\u7a0b\",\"type\":\"21\",\"weight\":0.607},{\"basic_word\":[\"\u56fe\"],\"etypes\":[],\"term\":\"\u56fe\",\"type\":\"21\",\"weight\":0.392}],\"qu_res_chosen\":\"{\\\"confidence\\\":100.0,\\\"domain_confidence\\\":0.0,\\\"extra_info\\\":{\\\"group_id\\\":\\\"1\\\",\\\"real_threshold\\\":\\\"1\\\",\\\"threshold\\\":\\\"0.6\\\"},\\\"from_who\\\":\\\"pow-slu-lev1\\\",\\\"intent\\\":\\\"INTENT_DREW\\\",\\\"intent_confidence\\\":100.0,\\\"intent_need_clarify\\\":false,\\\"match_info\\\":\\\"{\\\\\\\"group_id\\\\\\\":\\\\\\\"1\\\\\\\",\\\\\\\"id\\\\\\\":\\\\\\\"1599245\\\\\\\",\\\\\\\"informal_word\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"match_keywords\\\\\\\":\\\\\\\" kw_n:\u6d41\u7a0b\u56fe\\\\\\\",\\\\\\\"match_pattern\\\\\\\":\\\\\\\"[D:kw_n]\\\\\\\",\\\\\\\"ori_pattern\\\\\\\":\\\\\\\"[D:kw_n]\\\\\\\",\\\\\\\"ori_slots\\\\\\\":{\\\\\\\"confidence\\\\\\\":100.0,\\\\\\\"domain_confidence\\\\\\\":0.0,\\\\\\\"extra_info\\\\\\\":{},\\\\\\\"from_who\\\\\\\":\\\\\\\"smart_qu\\\\\\\",\\\\\\\"intent\\\\\\\":\\\\\\\"INTENT_DREW\\\\\\\",\\\\\\\"intent_confidence\\\\\\\":100.0,\\\\\\\"intent_need_clarify\\\\\\\":false,\\\\\\\"match_info\\\\\\\":\\\\\\\"[D:kw_n] kw_n:\u6d41\u7a0b\u56fe\\\\\\\",\\\\\\\"slots\\\\\\\":[{\\\\\\\"begin\\\\\\\":0,\\\\\\\"confidence\\\\\\\":100.0,\\\\\\\"father_idx\\\\\\\":-1,\\\\\\\"length\\\\\\\":6,\\\\\\\"name\\\\\\\":\\\\\\\"kw_n\\\\\\\",\\\\\\\"need_clarify\\\\\\\":false,\\\\\\\"normalized_word\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"original_word\\\\\\\":\\\\\\\"\u6d41\u7a0b\u56fe\\\\\\\",\\\\\\\"word_type\\\\\\\":\\\\\\\"\\\\\\\"}]},\\\\\\\"real_threshold\\\\\\\":1.0,\\\\\\\"threshold\\\\\\\":0.6000000238418579}\\\",\\\"slots\\\":[]}\\n\",\"raw_query\":\"\u6d41\u7a0b\u56fe\",\"sentiment_analysis\":{\"label\":\"1\",\"pval\":0.998},\"status\":0,\"timestamp\":0},\"schema\":{\"domain_confidence\":0.0,\"intent\":\"INTENT_DREW\",\"intent_confidence\":100.0,\"slots\":[]},\"status\":0}],\"bernard_status\":[{\"index\":0,\"step\":\"AFTER_DM_TRIGGER\"}],\"intervention\":{\"interv_qu_res\":\"\",\"interv_query\":\"\",\"qu_res_interved\":\"\",\"qu_res_original\":\"\",\"query_original\":\"\",\"type\":\"\",\"user_id\":\"\"},\"user_slots\":{}},\"dialog_state\":{\"contexts\":{\"dmkit\":{\"session\":\"\"}},\"intents\":[{\"index\":0,\"name\":\"INTENT_DREW\"}],\"user_slots\":{}},\"interactions\":[{\"interaction_id\":\"interaction-1555387557503-3374022661-8013-64\",\"request\":{\"bernard_level\":1,\"client_session\":\"{\\\"client_results\\\":\\\"\\\", \\\"candidate_options\\\":[]}\",\"hyper_params\":{\"slu_tags\":[]},\"query\":\"\u6d41\u7a0b\u56fe\",\"query_info\":{\"asr_candidates\":[],\"source\":\"ASR\",\"type\":\"TEXT\"},\"updates\":\"\",\"user_id\":\"52219\"},\"response\":{\"action_list\":[{\"action_id\":\"intent_drew_user_version_clarify\",\"confidence\":100.0,\"custom_reply\":\"\",\"refine_detail\":{\"clarify_reason\":\"slot_absent\",\"interact\":\"ask\",\"option_list\":[{\"info\":{\"name\":\"user_version\",\"text\":\"\u7248\u672c\"},\"option\":\"user_version\"}]},\"say\":\"\u8bf7\u6f84\u6e05\u4e00\u4e0b\uff1a\u7248\u672c\",\"type\":\"clarify\"}],\"msg\":\"ok\",\"qu_res\":{\"candidates\":[{\"confidence\":100.0,\"domain_confidence\":0.0,\"extra_info\":{\"group_id\":\"1\",\"real_threshold\":\"1\",\"threshold\":\"0.6\"},\"from_who\":\"pow-slu-lev1\",\"intent\":\"INTENT_DREW\",\"intent_confidence\":100.0,\"intent_need_clarify\":false,\"match_info\":\"{\\\"group_id\\\":\\\"1\\\",\\\"id\\\":\\\"1599245\\\",\\\"informal_word\\\":\\\"\\\",\\\"match_keywords\\\":\\\" kw_n:\u6d41\u7a0b\u56fe\\\",\\\"match_pattern\\\":\\\"[D:kw_n]\\\",\\\"ori_pattern\\\":\\\"[D:kw_n]\\\",\\\"ori_slots\\\":{\\\"confidence\\\":100.0,\\\"domain_confidence\\\":0.0,\\\"extra_info\\\":{},\\\"from_who\\\":\\\"smart_qu\\\",\\\"intent\\\":\\\"INTENT_DREW\\\",\\\"intent_confidence\\\":100.0,\\\"intent_need_clarify\\\":false,\\\"match_info\\\":\\\"[D:kw_n] kw_n:\u6d41\u7a0b\u56fe\\\",\\\"slots\\\":[{\\\"begin\\\":0,\\\"confidence\\\":100.0,\\\"father_idx\\\":-1,\\\"length\\\":6,\\\"name\\\":\\\"kw_n\\\",\\\"need_clarify\\\":false,\\\"normalized_word\\\":\\\"\\\",\\\"original_word\\\":\\\"\u6d41\u7a0b\u56fe\\\",\\\"word_type\\\":\\\"\\\"}]},\\\"real_threshold\\\":1.0,\\\"threshold\\\":0.6000000238418579}\",\"slots\":[]}],\"lexical_analysis\":[{\"basic_word\":[\"\u6d41\u7a0b\"],\"etypes\":[],\"term\":\"\u6d41\u7a0b\",\"type\":\"21\",\"weight\":0.607},{\"basic_word\":[\"\u56fe\"],\"etypes\":[],\"term\":\"\u56fe\",\"type\":\"21\",\"weight\":0.392}],\"qu_res_chosen\":\"{\\\"confidence\\\":100.0,\\\"domain_confidence\\\":0.0,\\\"extra_info\\\":{\\\"group_id\\\":\\\"1\\\",\\\"real_threshold\\\":\\\"1\\\",\\\"threshold\\\":\\\"0.6\\\"},\\\"from_who\\\":\\\"pow-slu-lev1\\\",\\\"intent\\\":\\\"INTENT_DREW\\\",\\\"intent_confidence\\\":100.0,\\\"intent_need_clarify\\\":false,\\\"match_info\\\":\\\"{\\\\\\\"group_id\\\\\\\":\\\\\\\"1\\\\\\\",\\\\\\\"id\\\\\\\":\\\\\\\"1599245\\\\\\\",\\\\\\\"informal_word\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"match_keywords\\\\\\\":\\\\\\\" kw_n:\u6d41\u7a0b\u56fe\\\\\\\",\\\\\\\"match_pattern\\\\\\\":\\\\\\\"[D:kw_n]\\\\\\\",\\\\\\\"ori_pattern\\\\\\\":\\\\\\\"[D:kw_n]\\\\\\\",\\\\\\\"ori_slots\\\\\\\":{\\\\\\\"confidence\\\\\\\":100.0,\\\\\\\"domain_confidence\\\\\\\":0.0,\\\\\\\"extra_info\\\\\\\":{},\\\\\\\"from_who\\\\\\\":\\\\\\\"smart_qu\\\\\\\",\\\\\\\"intent\\\\\\\":\\\\\\\"INTENT_DREW\\\\\\\",\\\\\\\"intent_confidence\\\\\\\":100.0,\\\\\\\"intent_need_clarify\\\\\\\":false,\\\\\\\"match_info\\\\\\\":\\\\\\\"[D:kw_n] kw_n:\u6d41\u7a0b\u56fe\\\\\\\",\\\\\\\"slots\\\\\\\":[{\\\\\\\"begin\\\\\\\":0,\\\\\\\"confidence\\\\\\\":100.0,\\\\\\\"father_idx\\\\\\\":-1,\\\\\\\"length\\\\\\\":6,\\\\\\\"name\\\\\\\":\\\\\\\"kw_n\\\\\\\",\\\\\\\"need_clarify\\\\\\\":false,\\\\\\\"normalized_word\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"original_word\\\\\\\":\\\\\\\"\u6d41\u7a0b\u56fe\\\\\\\",\\\\\\\"word_type\\\\\\\":\\\\\\\"\\\\\\\"}]},\\\\\\\"real_threshold\\\\\\\":1.0,\\\\\\\"threshold\\\\\\\":0.6000000238418579}\\\",\\\"slots\\\":[]}\\n\",\"raw_query\":\"\u6d41\u7a0b\u56fe\",\"sentiment_analysis\":{\"label\":\"1\",\"pval\":0.998},\"status\":0,\"timestamp\":0},\"schema\":{\"domain_confidence\":0.0,\"intent\":\"INTENT_DREW\",\"intent_confidence\":100.0,\"slots\":[]},\"status\":0},\"timestamp\":\"2019-04-16 12:05:57.503\"}],\"session_id\":\"session-1555387557414-3374022661-8013-26\"}", "bot_id": "42634"} service_unit_bot=remote:14.215.178.97:443|tm:509|ret:0 ret={"error_code":-1,"error_msg":"DM policy resolve failed"} tm=513.889851

**Comment by Yecgaa1** [comment]
？？？？

**Comment by lyc-baidu** [comment]
将判断条件里的string改成slot_val试一下

**Comment by Yecgaa1** [comment]
但是string不能被使用吗

**Comment by lyc-baidu** [comment]
只有在使用已定义变量进行模板填充时可以使用string。
流程图中的user_version不是已定义变量，而是UNIT解析得到的slot值，所以需要使用slot_val。

**Comment by Yecgaa1** [comment]
我还想了解一下，描述中slot val有tag是什么意思

**Comment by lyc-baidu** [comment]
从qu结果中提取槽位的键值
