### ISSUE TITLE
执行 sh deps.sh centos时编译报错，错误如下，请大佬告知提点下

### ISSUE THREAD

**Issue by zwysunshine** [baidu/unit-dmkit#48]
[ 68%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/brpc/details/ssl_helper.cpp.o
{standard input}: Assembler messages:
{standard input}:79083: Warning: end of file not at end of a line; newline inserted
{standard input}:81205: Error: unknown pseudo-op: `.b'
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [src/CMakeFiles/OBJ_LIB.dir/brpc/channel.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
[ 69%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/brpc/details/tcmalloc_extension.cpp.o
make[1]: *** [src/CMakeFiles/OBJ_LIB.dir/all] Error 2
make: *** [all] Error 2

**Comment by lyc-baidu** [comment]
centos的依赖是否已全部成功安装？

**Comment by lyc-baidu** [comment]
centos的依赖是否已全部成功安装？

**Comment by zwysunshine** [comment]
只需gflags  protobuf  leveldb这三个么？

**Comment by lyc-baidu** [comment]
deps.sh里面centos部分提到的所有依赖均需要安装
