### ISSUE TITLE
请问demo里的意图名称有个前缀：INTENT_，UNIT上配置意图名称也需要加上这个前缀吗？

### ISSUE THREAD

**Issue by healthicare** [baidu/unit-dmkit#49]
请问demo里的意图名称有个前缀：INTENT_，UNIT上配置意图名称也需要加上这个前缀吗？

**Comment by lyc-baidu** [comment]
需要

**Comment by healthicare** [comment]
多谢！

**Comment by healthicare** [comment]
您好，我之前在UNIT上写了不少意图，都是以ASK_做前缀的。现在需要配合DMKit，是不是都需要改成INTENT_做前缀？如果需要改成INTENT_做前缀，工作量很大，因为UNIT上无法修改意图名称，只能全部删除后重建。请问有没有比较省力的办法解决？
