### ISSUE TITLE
xml转json

### ISSUE THREAD

**Issue by zhuItGitHub** [baidu/unit-dmkit#50]
为什么自己画的流程图,导出为XML文件后.用python编译成json文件.但是Json文件里面没有任何参数.感觉xml转json失败了

**Comment by lyc-baidu** [comment]
可以把流程图或者xml贴出来看一下吗

**Comment by zhuItGitHub** [comment]
![image](https://user-images.githubusercontent.com/34933443/56463851-17514580-640f-11e9-80c6-46652cfb8087.png)
我们自己定义了一个超简单的流程图,想着先跑通一个案列.python 编译xml文件的时候没有报错,能正常生成对应的json文件.但就是json文件里什么数据都没有

**Comment by lyc-baidu** [comment]
图片不是很看得出来，方便贴一下xml吗？
