### ISSUE TITLE
学校项目做语音交互，需要用到dmkit，编译时遇到问题，求大家帮忙看看

### ISSUE THREAD

**Issue by cshuoshuo** [baidu/unit-dmkit#51]
不好意思打扰了，我想咨询下dmkit编译的问题，我按照教程完成了第1、2步。然后根据第三步，我理解的意思是在终端直接输入这行指令进行cmake编译，输入后反馈file_exists，如图所示，但是我又没有找到build目录在哪里，请问我这是哪里操作错了呢？实在抱歉，我程序小白，做交互想尝试使用一下dmkit，我在网络上的教程中没有找到解决方案，所以来求助，谢谢大家。
![111111](https://user-images.githubusercontent.com/49746634/56426216-0b1f9800-62ea-11e9-9b4a-d73c2d6fed74.jpg)
![22222](https://user-images.githubusercontent.com/49746634/56426219-0e1a8880-62ea-11e9-8381-d48ad57ec70c.jpg)
![33333](https://user-images.githubusercontent.com/49746634/56426223-107ce280-62ea-11e9-86eb-1ad4e3c9949f.jpg)

**Comment by lyc-baidu** [comment]
请先安装brew，安装方式请参考 https://brew.sh

**Comment by cshuoshuo** [comment]
谢谢

**Comment by cshuoshuo** [comment]
我已经安装了brew，然后我再按照readme里面的步骤进行编译，但是进行到cmake那一环节时又出现了之前的问题，请问在cmake那一环节具体该怎样操作呢？
<img width="1440" alt="图片" src="https://user-images.githubusercontent.com/49746634/56466108-95791080-643e-11e9-9eff-58cd15aa2a98.png">

**Comment by lyc-baidu** [comment]
检查一下brew是否安装失败，可以考虑换一个镜像进行安装

**Comment by cshuoshuo** [comment]
我再次重新安装了brew，执行了deps.sh的编译，然后进行cmake时出现了如下问题。
<img width="570" alt="图片" src="https://user-images.githubusercontent.com/49746634/56468326-7b9af600-645d-11e9-9d84-348236de1351.png">
brew的安装是显示安装成功了的，如下：
<img width="1192" alt="图片" src="https://user-images.githubusercontent.com/49746634/56468356-d3d1f800-645d-11e9-9e8a-c51a60f90da8.png">
麻烦大佬在帮我看下，另外，请问在cmake环节，直接键入mkdir _build && cd _build && cmake .. && make指令，然后回车就可以了嘛
谢谢

**Comment by lyc-baidu** [comment]
截图的是warning信息，有error信息吗？
如果_build目录已经存在，可以先把目录删除或者跳过mkdir _build命令执行。

**Comment by cshuoshuo** [comment]
谢谢，我又看了下，我在github下载的文件目录中的brpc文件夹里找到了-build文件夹，但是在其中我没有找到dmkit程序，请问我该如何运行它呢，谢谢谢谢，麻烦了
<img width="1440" alt="图片" src="https://user-images.githubusercontent.com/49746634/56482516-30352600-64f7-11e9-850a-ac736f2e17f0.png">

**Comment by lyc-baidu** [comment]
这个是brpc框架的编译目录，从截图看到目前brpc框架还没有编译成功，进行dmkit的编译是没有意义的。
重新执行一次deps.sh，看一下brpc编译具体的error信息。

**Comment by cshuoshuo** [comment]
好的，谢谢。我将deps.sh拖入终端，键入mac并执行，得到包含erro的字段结果如下：
<img width="1440" alt="图片" src="https://user-images.githubusercontent.com/49746634/56483678-fa477000-64fd-11e9-81d4-41481e05d6e2.png">
随后我键入mkdir _build && cd _build && cmake .. && make指令并执行，结果如下：
<img width="570" alt="图片" src="https://user-images.githubusercontent.com/49746634/56483707-32e74980-64fe-11e9-87e4-a51700fae815.png">
谢谢

**Comment by cshuoshuo** [comment]
找到了具体的erro位置
<img width="1440" alt="图片" src="https://user-images.githubusercontent.com/49746634/56483792-8bb6e200-64fe-11e9-95ff-b5d7a55afd73.png">

**Comment by lyc-baidu** [comment]
这个是brpc与protobuf最新版本(3.7)不兼容的问题，可以替换成3.6版本，参考https://github.com/apache/incubator-brpc/issues/656
以下命令可供参考：
`
brew uninstall protobuf
brew install protobuf@3.6
brew link --force protobuf@3.6
`

**Comment by cshuoshuo** [comment]
谢谢，麻烦了，我按照你说的三个命令进行了操作，随后键入mkdir _build && cd _build && cmake .. && make指令并执行，结果如下：
<img width="1440" alt="图片" src="https://user-images.githubusercontent.com/49746634/56484717-92942380-6503-11e9-9387-ac02782e14ec.png">
<img width="770" alt="图片" src="https://user-images.githubusercontent.com/49746634/56484765-c111fe80-6503-11e9-995e-a201789fe1ea.png">
还是显示 File exists

**Comment by lyc-baidu** [comment]
在brpc目录下执行deps.sh第59-63行，即
`rm -rf _build
mkdir -p _build
cd _build
cmake ..
make -j8`
编译完成后，再在dmkit目录下执行`mkdir _build && cd _build && cmake .. && make`

**Comment by cshuoshuo** [comment]
不好意思，谢谢谢谢，我尝试了第一步操作，得到结果显示如下：
<img width="570" alt="图片" src="https://user-images.githubusercontent.com/49746634/56485407-75ad1f80-6506-11e9-9465-9aa12d0a9035.png">

**Comment by lyc-baidu** [comment]
按下面步骤操作吧：
```
cd ~/Desktop/unit-dmkit-master/brpc
rm -rf _build
mkdir -p _build
cd _build
cmake ..
make -j8
```
编译完成后，执行：
```
cd ~/Desktop/unit-dmkit-master
mkdir _build && cd _build && cmake .. && make
```

**Comment by cshuoshuo** [comment]
谢谢谢谢！
