### ISSUE TITLE
意图名称的问题

### ISSUE THREAD

**Issue by healthicare** [baidu/unit-dmkit#53]
您好，我之前在UNIT上写了不少意图，都是以ASK_做前缀的。现在需要配合DMKit，是不是都需要改成INTENT_做前缀？如果需要改成INTENT_做前缀，工作量很大，因为UNIT上无法修改意图名称，只能全部删除后重建。请问有没有比较省力的办法解决？

**Comment by lyc-baidu** [comment]
使用UNIT上配置的意图名称即可

**Comment by healthicare** [comment]
那在用draw.io画图的时候，直接这么写吗：INTENT:INTENT_ASK_***。这样写可以吗？

**Comment by lyc-baidu** [comment]
INTENT:ASK_***

**Comment by healthicare** [comment]
OK，感谢！！
