### ISSUE TITLE
请问是一个意图一个xml还是一个技能一个xml

### ISSUE THREAD

**Issue by healthicare** [baidu/unit-dmkit#55]
请问是一个意图一个xml还是一个技能一个xml？

**Comment by healthicare** [comment]
或者这么问：是把一个技能里的所有意图画到一个draw.io文件里，还是把一个意图画到一个draw.io文件里？

**Comment by lyc-baidu** [comment]
一个技能里的所有意图画到一个draw.io文件里，生成一个xml

**Comment by healthicare** [comment]
明白了谢谢！
