### ISSUE TITLE
我们使用了DMkit，请问app应用的还是这个包吗

### ISSUE THREAD

**Issue by healthicare** [baidu/unit-dmkit#57]
我们使用了DMkit，请问app应用的还是这个包吗：http://ai.baidu.com/docs#/ASR-Android-SDK/top

**Comment by healthicare** [comment]
另外，H5界面能调用dmkit吗？

**Comment by lyc-baidu** [comment]
DM Kit提供的是HTTP服务，只要可以将请求包发送到搭建的服务即可

**Comment by healthicare** [comment]
了解了，谢谢！
