### ISSUE TITLE
ubuntu 上运行失败

### ISSUE THREAD

**Issue by xyl70** [baidu/unit-dmkit#59]
按示例配置了流量查询技能，已改好 conf/app/products.json 的 skill id;tot_tokens.josn文件。运行报错： ./dmkit
I0430 10:45:12.686876  3429 /home/xie/unit-dmkit/src/remote_service_manager.cpp:161] logid= Loading channel map...
E0430 10:45:12.708299  3429 /home/xie/unit-dmkit/brpc/src/brpc/policy/http_rpc_protocol.cpp:1310] Invalid address=`aip.baidubce.com'
E0430 10:45:12.708441  3429 /home/xie/unit-dmkit/brpc/src/brpc/channel.cpp:148] Fail to parse address=`https://aip.baidubce.com'
E0430 10:45:12.708486  3429 /home/xie/unit-dmkit/src/remote_service_manager.cpp:275] logid= Failed to init channel.
I0430 10:45:12.708525  3429 /home/xie/unit-dmkit/src/remote_service_manager.cpp:35] logid= Destroying service map...
E0430 10:45:12.708564  3429 /home/xie/unit-dmkit/src/remote_service_manager.cpp:64] logid= Failed to init RemoteServiceManager, cannot load channel map
E0430 10:45:12.708602  3429 /home/xie/unit-dmkit/src/dialog_manager.cpp:43] logid= Failed to init _remote_service_manager
E0430 10:45:12.708638  3429 /home/xie/unit-dmkit/src/app_container.cpp:62] logid= failed to init application!!!
E0430 10:45:12.708674  3429 /home/xie/unit-dmkit/src/server.cpp:82] logid= Fail to init http_svc
I0430 10:45:12.708712  3429 /home/xie/unit-dmkit/src/file_watcher.cpp:71] FileWatcher unregistering file 
I0430 10:45:12.708748  3429 /home/xie/unit-dmkit/src/file_watcher.cpp:71] FileWatcher unregistering file conf/app/remote_services.json
I0430 10:45:12.708785  3429 /home/xie/unit-dmkit/src/file_watcher.cpp:71] FileWatcher unregistering file

**Comment by lyc-baidu** [comment]
ping aip.baidubce.com，检查一下网络是否正常
