### ISSUE TITLE
deamon mode support

### ISSUE THREAD

**Issue by tfzxyinhao** [baidu/unit-dmkit#60]
need run uskit as deamon mode. 
please support it.

**Comment by lyc-baidu** [comment]
If you need run uskit as deamon mode, please submit issue at https://github.com/baidu/unit-uskit
DM Kit hasn't supported daemon yet. You could try to use nohup.

**Comment by tfzxyinhao** [comment]
dmkit 同样需要支持deamon 模式运行比较好

**Comment by lyc-baidu** [comment]
目前暂时没有支持daemon模式的计划
