### ISSUE TITLE
提示选择的问题

### ISSUE THREAD

**Issue by healthicare** [baidu/unit-dmkit#62]
您好，我在UNIT上配置出现：一个值，比如失眠，在2个词槽中出现了。
在UNIT上测试，识别时会提示选择哪个意图。
但是app集成的时候，提示识别失败。
请问怎么处理，谢谢！

**Comment by lyc-baidu** [comment]
action_type是什么呢？
是否方便提供相关截图和日志作参考？

**Comment by healthicare** [comment]
谢谢，不用了，已经解决。
