### ISSUE TITLE
使用service_http_get出问题

### ISSUE THREAD

**Issue by kongkongthu** [baidu/unit-dmkit#63]
![image](https://user-images.githubusercontent.com/32895120/57368812-a8217280-71be-11e9-8b9e-cbe99419ac0a.png)
如上图，看意思是这个函数没有注册，但是这不是dmkit系统默认的函数吗？

**Comment by kongkongthu** [comment]
反正没有正确返回数据，是哪里出问题了呢？

**Comment by lyc-baidu** [comment]
service_http_get后接冒号

**Comment by kongkongthu** [comment]
正解，问题解决。而且函数名后面的参数不能加引号，不然也会出错。
