### ISSUE TITLE
params.request_param  参数传递问题

### ISSUE THREAD

**Issue by xyl70** [baidu/unit-dmkit#64]
PARAM:repuest_param:name={%client_name%}
取不到值，问题出在那里？
流量图配置：
PARAM:repuest_param:name={%client_name%}
PARAM:func_val:addr=wuka_get_addr:{%name%}
BOT:请问你的收货地址是{%addr%}，对吗？

c++ 自定义函数代码：
int get_data_address(const std::vector<std::string> &args,
                     const RequestContext &context, std::string &result)
{
    (void)context;
    if (args.size() < 1)
    {
        return -1;
    }
    std::string addr = "广州市白云区三元里大道(";
    addr.append(args[0]);
    addr.append(")");
    result = addr;
    return 0;
}

客户端，python代码 ：
name = raw_input("请输入客户名字: ") #"张三"     
payload = {
            "version": "2.0",
            "bot_id": "47230",
            "log_id": logid,
            "request": {
                "user_id": user_id,
                "query": user_input,
                "query_info": {
                    "type": "TEXT",
                    "source": "ASR",
                    "asr_candidates": []
                },
                "updates": "",
                "client_session": "{\"client_results\":\"\", \"candidate_options\":[], \"client_name\":" + name + "}",
                "bernard_level": 1
            },
            "bot_session": session
        }

返回的结果是：
BOT:
请问你的收货地址是广州市白云区三元里大道()，对吗？

**Comment by lyc-baidu** [comment]
client_session的值需要转义

**Comment by xyl70** [comment]
已经有转议，copy代码没显示，这个请求没问题

**Comment by lyc-baidu** [comment]
方便把client_session截图看看吗？还有json配置中设置name的部分也贴出来看看

**Comment by xyl70** [comment]
- [ ] 

- [ ] 

- [ ] -

**Comment by xyl70** [comment]
代码截图：
![屏幕快照 2019-05-10 09 14 22](https://user-images.githubusercontent.com/34577341/57496271-9e098c00-7304-11e9-95b3-4de1d2681227.png)
流程图：
![屏幕快照 2019-05-10 09 29 46](https://user-images.githubusercontent.com/34577341/57496578-5d127700-7306-11e9-87d3-fef874dc9430.png)
json配置：
{
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "请问你的收货地址是{%addr%}，对吗？"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "001"
        }
      }
    ], 
    "params": [
      {
        "name": "name", 
        "type": "repuest_param", 
        "value": "{%client_name%}"
      }, 
      {
        "name": "addr", 
        "type": "func_val", 
        "value": "wuka_get_addr:{%name%}"
      }
    ], 
    "trigger": {
      "intent": "INTENT_YES", 
      "slots": [], 
      "state": ""
    }
  }, 
查看实际json内容：{
    "dialog_state": {
        "contexts": {
            "dmkit": {
                "session": "{\"domain\":\"47230\",\"state\":\"001\",\"context\":{\"dmkit_param_last_tts\":\"请问你的收货地址是广州市白云区三元里大道()，对吗？\"}}"
            }
        },
        "intents": [
            {
                "index": 0,
                "name": "INTENT_YES"
            },
            {
                "index": 1,
                "name": "INTENT_YES"
            }
        ],
        "user_slots": []
    },
    "request": {
        "bernard_level": 1,
        "client_session": "{\"client_results\":\"\", \"candidate_options\":[], \"client_name\":张三}",
        "hyper_params": {
            "slu_tags": []
        },
        "query": "是的",
        "query_info": {
            "asr_candidates": [],
            "source": "ASR",
            "type": "TEXT"
        },
        "updates": "",
        "user_id": "99611"
    },
    "response": {
        "action_list": [
            {
                "action_id": "",
                "confidence": 0,
                "custom_reply": "",
                "refine_detail": {
                    "clarify_reason": "",
                    "interact": "",
                    "option_list": []
                },
                "say": "",
                "type": "understood"
            }
        ],
        "msg": "ok",
        "qu_res": {
            "candidates": [
                {
                    "confidence": 100,
                    "domain_confidence": 0,
                    "extra_info": {
                        "group_id": "2",
                        "real_threshold": "1",
                        "threshold": "0.7"
                    },
                    "from_who": "pow-slu-lev1",
                    "intent": "INTENT_YES",
                    "intent_confidence": 100,
                    "intent_need_clarify": false,
                    "match_info": "{\"group_id\":\"2\",\"id\":\"1147902\",\"informal_word\":\"是\\t的\",\"match_keywords\":\" kw_yes:是的\",\"match_pattern\":\"[W:0-2][D:kw_yes][W:0-4]\",\"ori_pattern\":\"[W:0-2][D:kw_yes][W:0-4]\",\"ori_slots\":{\"confidence\":100.0,\"domain_confidence\":0.0,\"extra_info\":{},\"from_who\":\"smart_qu\",\"intent\":\"INTENT_YES\",\"intent_confidence\":100.0,\"intent_need_clarify\":false,\"match_info\":\"[W:0-2][D:kw_yes][W:0-4] kw_yes:是的\",\"slots\":[{\"begin\":0,\"confidence\":100.0,\"father_idx\":-1,\"length\":4,\"name\":\"kw_yes\",\"need_clarify\":false,\"normalized_word\":\"\",\"original_word\":\"是的\",\"word_type\":\"\"}]},\"real_threshold\":1.0,\"threshold\":0.6999999880790710}",
                    "slots": []
                }
            ],
            "lexical_analysis": [
                {
                    "basic_word": [
                        "是"
                    ],
                    "etypes": [],
                    "term": "是",
                    "type": "34",
                    "weight": 0.487
                },
                {
                    "basic_word": [
                        "的"
                    ],
                    "etypes": [],
                    "term": "的",
                    "type": "33",
                    "weight": 0.512
                }
            ],
            "qu_res_chosen": "{\"confidence\":100.0,\"domain_confidence\":0.0,\"extra_info\":{\"group_id\":\"2\",\"real_threshold\":\"1\",\"threshold\":\"0.7\"},\"from_who\":\"cur_set\",\"intent\":\"INTENT_YES\",\"intent_confidence\":100.0,\"intent_need_clarify\":false,\"match_info\":\"{\\\"group_id\\\":\\\"2\\\",\\\"id\\\":\\\"1147902\\\",\\\"informal_word\\\":\\\"是\\\\t的\\\",\\\"match_keywords\\\":\\\" kw_yes:是的\\\",\\\"match_pattern\\\":\\\"[W:0-2][D:kw_yes][W:0-4]\\\",\\\"ori_pattern\\\":\\\"[W:0-2][D:kw_yes][W:0-4]\\\",\\\"ori_slots\\\":{\\\"confidence\\\":100.0,\\\"domain_confidence\\\":0.0,\\\"extra_info\\\":{},\\\"from_who\\\":\\\"smart_qu\\\",\\\"intent\\\":\\\"INTENT_YES\\\",\\\"intent_confidence\\\":100.0,\\\"intent_need_clarify\\\":false,\\\"match_info\\\":\\\"[W:0-2][D:kw_yes][W:0-4] kw_yes:是的\\\",\\\"slots\\\":[{\\\"begin\\\":0,\\\"confidence\\\":100.0,\\\"father_idx\\\":-1,\\\"length\\\":4,\\\"name\\\":\\\"kw_yes\\\",\\\"need_clarify\\\":false,\\\"normalized_word\\\":\\\"\\\",\\\"original_word\\\":\\\"是的\\\",\\\"word_type\\\":\\\"\\\"}]},\\\"real_threshold\\\":1.0,\\\"threshold\\\":0.6999999880790710}\",\"slots\":[]}\n",
            "raw_query": "是的",
            "sentiment_analysis": {
                "label": "1",
                "pval": 0.997
            },
            "status": 0,
            "timestamp": 0
        },
        "schema": {
            "domain_confidence": 0,
            "intent": "INTENT_YES",
            "intent_confidence": 100,
            "slots": [],
            "slu_tags": []
        },
        "status": 0
    }
}

**Comment by lyc-baidu** [comment]
client_session中的name前后需要加上转义后的双引号

**Comment by xyl70** [comment]
看错了吧：
在实际的jon内容中："client_session": "{"client_results":"", "candidate_options":[], "client_name":张三}",
是正常的呀

**Comment by lyc-baidu** [comment]
"client_session": "{"client_results":"", "candidate_options":[], "client_name":**"张三"**}"

**Comment by xyl70** [comment]
明白了

**Comment by xyl70** [comment]
还是没有传递到参数:
![屏幕快照 2019-05-10 10 06 27](https://user-images.githubusercontent.com/34577341/57497727-710ca780-730b-11e9-880c-668628ec34ef.png)

**Comment by lyc-baidu** [comment]
配置打成了repuest_param

**Comment by xyl70** [comment]
奇怪，还是不行:
![屏幕快照 2019-05-10 14 09 55](https://user-images.githubusercontent.com/34577341/57506115-66630a00-732d-11e9-84f2-a51554a0bd80.png)

完整的json配置：
[
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "好的，我们将{%date%}前安排人给你送卡，请您这两天保持电话畅通通并提前准备好身份证原件以便开户"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "002"
        }
      }
    ], 
    "params": [
      {
        "name": "name", 
        "type": "request_param", 
        "value": "{%client_name%}"
      }, 
      {
        "name": "date", 
        "type": "func_val", 
        "value": "wuka_get_date:{%name%}"
      }
    ], 
    "trigger": {
      "intent": "INTENT_YES", 
      "slots": [], 
      "state": "001"
    }
  }, 
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "哦，请问您修改的地址是那里呢？"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "005"
        }
      }
    ], 
    "params": [], 
    "trigger": {
      "intent": "INTENT_NO", 
      "slots": [], 
      "state": "001"
    }
  }, 
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "感谢您的接听，祝你生活愉快，再见！"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "003"
        }
      }
    ], 
    "params": [], 
    "trigger": {
      "intent": "INTENT_YES", 
      "slots": [], 
      "state": "002"
    }
  }, 
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "感谢您的接听，祝你生活愉快，再见！"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "003"
        }
      }
    ], 
    "params": [], 
    "trigger": {
      "intent": "INTENT_YES", 
      "slots": [], 
      "state": "006"
    }
  }, 
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "请问你的收货地址是{%addr%}，对吗？"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "001"
        }
      }
    ], 
    "params": [
      {
        "name": "name", 
        "type": "request_param", 
        "value": "{%client_name%}"
      }, 
      {
        "name": "addr", 
        "type": "func_val", 
        "value": "wuka_get_addr:{%name%}"
      }
    ], 
    "trigger": {
      "intent": "INTENT_YES", 
      "slots": [], 
      "state": ""
    }
  }, 
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "对不起，打扰了，再见"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "004"
        }
      }
    ], 
    "params": [], 
    "trigger": {
      "intent": "INTENT_NO", 
      "slots": [], 
      "state": ""
    }
  }, 
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "好的，已为你修改好地址了，我们将于{%date%}前安排人给你送卡，请你保持电话畅通并提前准备好身份证原件以便开户"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "006"
        }
      }
    ], 
    "params": [
      {
        "name": "name", 
        "type": "request_param", 
        "value": "{%client_name%}"
      }, 
      {
        "name": "date", 
        "type": "func_val", 
        "value": "wuka_get_date:{%name%}"
      }
    ], 
    "trigger": {
      "intent": "INTENT_CHECK_ADDR", 
      "slots": [
        "user_addr"
      ], 
      "state": "005"
    }
  }, 
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "{%dmkit_param_last_tts%}"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "{%state%}"
        }
      }
    ], 
    "params": [
      {
        "name": "state", 
        "type": "session_state", 
        "value": ""
      }
    ], 
    "trigger": {
      "intent": "INTENT_REPEAT", 
      "slots": [], 
      "state": ""
    }
  }, 
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "嗯，您说？"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "007"
        }
      }
    ], 
    "params": [
      {
        "name": "dmkit_param_context_state", 
        "type": "session_state", 
        "value": ""
      }, 
      {
        "name": "dmkit_param_context_tts", 
        "type": "string", 
        "value": "{%dmkit_param_last_tts%}"
      }
    ], 
    "trigger": {
      "intent": "INTENT_WAIT", 
      "slots": [], 
      "state": ""
    }
  }, 
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "{%dmkit_param_context_tts%}"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "008"
        }
      }
    ], 
    "params": [], 
    "trigger": {
      "intent": "INTENT_CONTINUE", 
      "slots": [], 
      "state": "007"
    }
  }
]

**Comment by xyl70** [comment]
问题应该不是在自定义函数之后，在 调用传参及之前，c++的另一个函数：
int get_data_date(const std::vector<std::string> &args,
                  const RequestContext &context, std::string &result)
{
    (void)context;
    if (args.size() < 1)
    {
        return -1;
    }
    time_t now = time(0);
    tm *gmtm = gmtime(&now);
    char date[50];
    sprintf(date, "%02d月%02d日(%s)", gmtm->tm_mon, gmtm->tm_mday + 3, args[0].c_str());
    result = date;

    return 0;
}

**Comment by lyc-baidu** [comment]
"value": "{%client_name%}" 修改为 "value": "client_name"

**Comment by xyl70** [comment]
是这样了，结果输出正确了
