### ISSUE TITLE
如何才能触发dm 调整额度demo中的某个逻辑

### ISSUE THREAD

**Issue by xiaomaofish** [baidu/unit-dmkit#69]
把调整信用卡额度demo的xml文件导入draw.io，最上面的一个应答是“BOT: 您需要调整临时额度还是固定额度？| 请问您要调整固定额度还是临时额度呢？”，请问如何才能触发这个应答？
    我在对话模板中加了一个“你好”的模板内容，对应的意图是INTENT_ADJUST_QUOTA，按照我的理解，当我输入“你好”时，匹配到了INTENT_ADJUST_QUOTA，且没有任何词槽填充，应该应答“BOT: 您需要调整临时额度还是固定额度？| 请问您要调整固定额度还是临时额度呢？”，可实际上应答的是意图中第一个词槽的澄清内容：请澄清一下类型。
   如果能够明确知道如何能够触发dm流程中的某个步骤，我们也就能明确的用dm设计自己的对话逻辑，但目前我的困惑就是demo中那些逻辑不知道输入什么才能明确的触发它们。

**Comment by lyc-baidu** [comment]
可以先在UNIT平台先尝试一下看看query是否有结果，只有在有满足结果（非失败或澄清）的前提下才会进入dmkit的逻辑。
