### ISSUE TITLE
main(sys.argv[1], sys.argv[2])

### ISSUE THREAD

**Issue by Yecgaa1** [baidu/unit-dmkit#71]
似乎旧版没有遇到过这个问题，想问一下原因

**Comment by Yecgaa1** [comment]
测试代码python tools/bot_emulator.py 54911
已配置/unit-dmkit/_build/conf/app/bot_tokens.json

**Comment by lyc-baidu** [comment]
可以详细描述一下问题吗

**Comment by Yecgaa1** [comment]
在使用bot_emulator.py 测试时出现main(sys.argv[1], sys.argv[2]) 错误

**Comment by lyc-baidu** [comment]
有完整的错误日志吗？

**Comment by Yecgaa1** [comment]
？

**Comment by Yecgaa1** [comment]
就是在运行bot_emulator.py时还没开始对话就报错了

**Comment by lyc-baidu** [comment]
只有这一行吗？
