### ISSUE TITLE
Token应该是什么?

### ISSUE THREAD

**Issue by henrypig** [baidu/unit-dmkit#72]
输入信息提示Token无效,请问是什么原因
python bot_emulator.py 11669 /home/willhua/dialog/baidu/unit-dmkit/conf/app/bot_tokens.json
-----------------------------------------------------------------
input:
h
BOT:
ERROR: Access token invalid or no longer valid
-----------------------------------------------------------------

**Comment by lyc-baidu** [comment]
DMKit运行环境下的bot_token.json是否已针对对应的bot_id（11669）填写api_key及secret_key？如果已填写，access token参数置空即可，即
`python bot_emulator.py 11669 ""`

**Comment by henrypig** [comment]
bot_token.json 内容如下:
{
    "1234": {
        "api_key": "wvvPzeyQfWQj7r6hxNobxmQA",
        "secret_key": "v2hQ20hLmkStbgNSUioslGN6EbyiAdc9"  
    }
}

报了新问题:ERROR: Failed to get access token

willhua@super_x:~/dialog/baidu/unit-dmkit/tools$ python bot_emulator.py 1234 ""
-----------------------------------------------------------------
input:
hi
BOT:
ERROR: Failed to get access token
-----------------------------------------------------------------
input:

**Comment by lyc-baidu** [comment]
把1234改为你创建的技能ID

**Comment by henrypig** [comment]
products.json里配了三个默认的技能，如下：
{
    "default": {
        "4050": {
            "score": 1,
            "conf_path": "conf/app/demo/cellular_data.json"
        },
        "1234": {
            "score": 1,
            "conf_path": "conf/app/demo/quota_adjust.json"
        },
        "11669": {
            "score": 1,
            "conf_path": "conf/app/demo/book_hotel.json"
        }
    }
}
我现在用的就是其中的一个，我也在UNIT平台上新建了一个技能，但找不到方法把这个技能转成JSON文件给我本地的DMKit加载。请问把UNIT平台上新建的技能加载到我本地的DMKit上。

**Comment by lyc-baidu** [comment]
UNIT平台上新建的技能ID是多少呢？
