### ISSUE TITLE
dmkit重载失败

### ISSUE THREAD

**Issue by Yecgaa1** [baidu/unit-dmkit#73]

**Comment by Yecgaa1** [comment]
[图片]

**Comment by Yecgaa1** [comment]
![TIM图片20190621184734](https://user-images.githubusercontent.com/38446391/59917639-0ba4ee00-9455-11e9-83d5-4d7dca609f87.png)

**Comment by lyc-baidu** [comment]
conf/app/demo/first.json是否合法json？

**Comment by Yecgaa1** [comment]
使用run.py转换得到

**Comment by Yecgaa1** [comment]
转换时没有报错

**Comment by lyc-baidu** [comment]
json文件是否放在_build目录下的conf中？

**Comment by Yecgaa1** [comment]
应该是的，我需要发json给您看看吗

**Comment by lyc-baidu** [comment]
看一下json文件吧，以及目录层级的截图

**Comment by Yecgaa1** [comment]
![TIM图片20190621184734](https://user-images.githubusercontent.com/38446391/59919070-106ba100-9459-11e9-9c6d-09d260c4e6ea.png)

[first.zip](https://github.com/baidu/unit-dmkit/files/3314205/first.zip)

**Comment by lyc-baidu** [comment]
我看这个json是经过转义的，是否方便把运行run.py前的xml也发来看看？

**Comment by Yecgaa1** [comment]
[first.zip](https://github.com/baidu/unit-dmkit/files/3314227/first.zip)

**Comment by lyc-baidu** [comment]
我这里生成的json是正常的，你可以把json文件中的\n以及前后的"b'"、"'"都去掉，先试试看服务能不能启动成功

**Comment by Yecgaa1** [comment]
您的意思是我的run.py有问题

**Comment by Yecgaa1** [comment]
xml是没问题的？

**Comment by lyc-baidu** [comment]
xml没问题的，问题也有可能出现在python环境上，先按上面的方法改改看能不能成功

**Comment by Yecgaa1** [comment]
因为我还遇到了另一个问题，3.7.3的python不能运行bot_emulator.py,结果跳到了2.7运行，结果run.py不能在2.7运行，在3.7中又提醒权限不足，十分苦恼。最后发现环境中有3.6的，但是完整性未知

**Comment by Yecgaa1** [comment]
那么应该在python几中都能运行呢

**Comment by lyc-baidu** [comment]
python2.7下应该是可以的，run.py在2.7运行的错误消息是？
