### ISSUE TITLE
dmkit非法指令（核心已转储）

### ISSUE THREAD

**Issue by Yecgaa1** [baidu/unit-dmkit#74]
root@zqw-IdeaCentre-Q180:/home/xutongxin/unit-dmkit/_build# ./dmkit
I0706 23:33:02.935870  6866 /home/xutongxin/unit-dmkit/src/remote_service_manager.cpp:161] logid= Loading channel map...
I0706 23:33:02.964318  6866 /home/xutongxin/unit-dmkit/src/remote_service_manager.cpp:303] logid= Loaded service unit_bot
I0706 23:33:02.965284  6866 /home/xutongxin/unit-dmkit/src/remote_service_manager.cpp:303] logid= Loaded service token_auth
I0706 23:33:02.965708  6874 /home/xutongxin/unit-dmkit/brpc/src/brpc/details/naming_service_thread.cpp:185] brpc::policy::DomainNamingService("127.0.0.1:5000"): added 1
I0706 23:33:02.965910  6866 /home/xutongxin/unit-dmkit/src/remote_service_manager.cpp:303] logid= Loaded service hotel_service
I0706 23:33:02.965992  6866 /home/xutongxin/unit-dmkit/src/file_watcher.cpp:54] FileWatcher registering file conf/app/remote_services.json
I0706 23:33:02.966313  6866 /home/xutongxin/unit-dmkit/src/dialog_manager.cpp:46] logid= _remote_service_manager init done
I0706 23:33:02.966400  6878 /home/xutongxin/unit-dmkit/src/file_watcher.cpp:86] Watcher thread starting...
I0706 23:33:02.966663  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:297] logid= Loading policies for product: default
I0706 23:33:02.966761  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:319] logid= Loading policies for domain 4050 from conf/app/demo/cellular_data.json
I0706 23:33:02.967156  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.967270  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.967446  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.967572  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.967723  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.967808  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.967892  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.968049  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.968140  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.968226  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.968297  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.968374  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.968471  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.968562  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.968635  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:369] logid= initializing domain policy...
I0706 23:33:02.968675  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:371] logid= finish initializing domain policy...
I0706 23:33:02.968712  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:326] logid= Loaded policies for domain 4050
I0706 23:33:02.968813  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:319] logid= Loading policies for domain 1234 from conf/app/demo/quota_adjust.json
I0706 23:33:02.969204  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.969319  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.969444  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.969643  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.969770  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.969857  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.969957  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.970059  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.970168  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.970314  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.970422  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.970496  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.970584  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.970657  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.970766  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.970855  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.970987  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:369] logid= initializing domain policy...
I0706 23:33:02.971051  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:371] logid= finish initializing domain policy...
I0706 23:33:02.971120  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:326] logid= Loaded policies for domain 1234
I0706 23:33:02.971169  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:319] logid= Loading policies for domain 11669 from conf/app/demo/book_hotel.json
I0706 23:33:02.971532  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.971672  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.971813  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.971881  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.971946  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.972033  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.972109  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.972178  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:357] logid= loading policy...
I0706 23:33:02.972259  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:369] logid= initializing domain policy...
I0706 23:33:02.972310  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:371] logid= finish initializing domain policy...
I0706 23:33:02.972377  6866 /home/xutongxin/unit-dmkit/src/policy_manager.cpp:326] logid= Loaded policies for domain 11669
I0706 23:33:02.972463  6866 /home/xutongxin/unit-dmkit/src/file_watcher.cpp:54] FileWatcher registering file conf/app/products.json
I0706 23:33:02.973650  6866 /home/xutongxin/unit-dmkit/src/file_watcher.cpp:54] FileWatcher registering file conf/app/bot_tokens.json
I0706 23:33:02.973778  6866 /home/xutongxin/unit-dmkit/src/dialog_manager.cpp:57] logid= _policy_manager init done
I0706 23:33:02.974171  6866 /home/xutongxin/unit-dmkit/src/server.cpp:104] logid= Starting server...
I0706 23:33:02.981403  6866 /home/xutongxin/unit-dmkit/brpc/src/brpc/server.cpp:982] Server[dmkit::HttpServiceImpl] is serving on port=8010 and internal_port=8011.
I0706 23:33:02.981745  6866 /home/xutongxin/unit-dmkit/brpc/src/brpc/server.cpp:985] Check out http://zqw-IdeaCentre-Q180:8011 in web browser.
非法指令 (核心已转储)

**Comment by lyc-baidu** [comment]
日志看起来没有问题。请问是启动阶段还是请求阶段引起的异常？是否有产生core文件？

**Comment by Yecgaa1** [comment]
启动阶段，如何验证是否产生？

**Comment by lyc-baidu** [comment]
默认生成在_build目录下，也可以查看/proc/sys/kernel/core_pattern是否有对保存路径修改。
此外，从已有的日志来看，服务是正常启动的，也可以检查一下是否可以发送请求，以及检查内存使用情况。
