### ISSUE TITLE
请问下分支比较大小ge，lt等怎么比较时间大小比较大小user_time_from:上个礼拜一(2019-07-15) user_time_to:下个礼拜一(2019-07-29)

### ISSUE THREAD

**Issue by bigfool-li** [baidu/unit-dmkit#76]

**Comment by bigfool-li** [comment]
![image](https://user-images.githubusercontent.com/23164179/61622798-164ae100-aca8-11e9-8ca5-5953e138d19b.png)

**Comment by HuangLK** [comment]
可以在params中定义*一个时间大小对比的结果变量*，如：
```
    {
                "name": "time_compare_result",
                "type": "func_val",
                "value": "user_compare_time:{%lhs%},{%rhs%},"
    }
```
需要自己实现`user_compare_time`，参考[params中变量类型列表及其说明](https://github.com/baidu/unit-dmkit/blob/master/docs/tutorial.md#params%E4%B8%AD%E5%8F%98%E9%87%8F%E7%B1%BB%E5%9E%8B%E5%88%97%E8%A1%A8%E5%8F%8A%E5%85%B6%E8%AF%B4%E6%98%8E)

**Comment by bigfool-li** [comment]
![image](https://user-images.githubusercontent.com/23164179/61698293-6d65ba00-ad6b-11e9-9d10-b9b0901abcd8.png)
![image](https://user-images.githubusercontent.com/23164179/61698331-840c1100-ad6b-11e9-81ee-a8c7f1908203.png)
![image](https://user-images.githubusercontent.com/23164179/61698404-a6059380-ad6b-11e9-801b-b96a662d88da.png)
![image](https://user-images.githubusercontent.com/23164179/61698437-b0c02880-ad6b-11e9-8e55-278a1749666f.png)
![image](https://user-images.githubusercontent.com/23164179/61698454-ba499080-ad6b-11e9-894b-51bfa785fc9c.png)

**Comment by bigfool-li** [comment]
现在配置demo.cpp,demo.h,  也在外面注册了。重新编译配置传参，还是报段错误(吐核)

**Comment by bigfool-li** [comment]
![image](https://user-images.githubusercontent.com/23164179/61698909-786d1a00-ad6c-11e9-9806-6fb00b0713bc.png)
这种日期打的不详细，也不知道具体错误

**Comment by bigfool-li** [comment]
![image](https://user-images.githubusercontent.com/23164179/61699512-a30ba280-ad6d-11e9-8e69-c466fc1115f5.png)
这种日志打的也不知道啥错误

**Comment by bigfool-li** [comment]
看了下police_manager.cpp 577行那边， slot名字 param.name读进来了， 但param.value是空值，在split的时候应该报错了。
![image](https://user-images.githubusercontent.com/23164179/61709426-d0fae200-ad81-11e9-9503-6837bdfac92b.png)
![image](https://user-images.githubusercontent.com/23164179/61709451-e3751b80-ad81-11e9-8a07-f29cc5d6b4e8.png)
请问是我那个地方少配置了吗

**Comment by bigfool-li** [comment]
话术澄清的slot是不是解析不到

**Comment by HuangLK** [comment]
可以看下warning日志有没有什么有用信息
