### ISSUE TITLE
php版本是不是已经停止维护了

### ISSUE THREAD

**Issue by 18272852021** [baidu/unit-dmkit#79]
如题

**Comment by 18272852021** [comment]
READEME.md里介绍的xml文件没有，执行完speak包含的目录又不对，调整完之后总让选择1或2。

**Comment by xiaom5248** [comment]
> READEME.md里介绍的xml文件没有，执行完speak包含的目录又不对，调整完之后总让选择1或2。

按照指南在unit上建好技能了吗？1和2是选择实例的bot，1是额度调整bot，2是流量查询bot

**Comment by xiaom5248** [comment]
另外有什么问题可以去那个库下面提issue
