### ISSUE TITLE
示例场景那里的意图全部都是对话意图吗

### ISSUE THREAD

**Issue by urcllr** [baidu/unit-dmkit#8]
https://github.com/baidu/unit-dmkit/blob/master/docs/demo_bots.md 这里两个示例BOT的意图都是对话意图吗？
还有这些意图的答复项是选文本类型然后随便填些内容就行了吗？

**Comment by jiyoushengbd** [comment]
1. 是对话意图；
2. 在bot设置页面中，将『BOT回应设置』设置为『使用DM Kit配置』，平台上即无需填写答复内容，具体答复内容及函数执行可在DMKit中进行配置。
