### ISSUE TITLE
draw图表定义session context问题

### ISSUE THREAD

**Issue by effort-effort** [baidu/unit-dmkit#82]
draw定义的图表，编译后的json文件session context仍为空，我这个定义是否正确呢
PARAM:string:dmkit_param_context_dep={%dep%}

**Comment by HuangLK** [comment]
可视化界面定义dmkit_param_context_xxx是在json文件的param内部定义，不会直接出现在session context里，可以参考[demo cellular_data](https://github.com/baidu/unit-dmkit/blob/master/conf/app/demo/cellular_data.xml):
https://github.com/baidu/unit-dmkit/blob/master/conf/app/demo/cellular_data.json#L416

**Comment by effort-effort** [comment]
恩，我知道怎么设置了
 



------------------ 原始邮件 ------------------
发件人: "Huanglk"<notifications@github.com>; 
发送时间: 2019年9月3日(星期二) 中午1:01
收件人: "baidu/unit-dmkit"<unit-dmkit@noreply.github.com>; 
抄送: "海籽"<1258849627@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [baidu/unit-dmkit] draw图表定义session context问题 (#82)




可视化界面定义dmkit_param_context_xxx是在json文件的param内部定义，不会直出现在session context里，可以参考demo cellular_data:
 https://github.com/baidu/unit-dmkit/blob/master/conf/app/demo/cellular_data.json#L416
