### ISSUE TITLE
"error_msg":"DM policy resolve failed"

### ISSUE THREAD

**Issue by syschen** [baidu/unit-dmkit#85]
![image](https://user-images.githubusercontent.com/8849212/64410506-c55b4480-d0bd-11e9-9310-bf0e531c1fe2.png)
求助，帮忙看下感觉卡到这一步了。

**Comment by HuangLK** [comment]
麻烦发一下对应的policy配置，目前的问题是有意图但是没有命中对应的policy

**Comment by syschen** [comment]
> 麻烦发一下对应的policy配置，目前的问题是有意图但是没有命中对应的policy

![image](https://user-images.githubusercontent.com/8849212/64411454-c0979000-d0bf-11e9-917e-372c10f28c9f.png)
刚开始玩，就弄了个简单的

![image](https://user-images.githubusercontent.com/8849212/64411479-d442f680-d0bf-11e9-9bf5-66eed7aec231.png)

这是xml的配置

**Comment by syschen** [comment]
![image](https://user-images.githubusercontent.com/8849212/64411532-f2a8f200-d0bf-11e9-80bc-86109b4f68c6.png)
刚开始玩，就弄了个简单的

![image](https://user-images.githubusercontent.com/8849212/64411550-fe94b400-d0bf-11e9-9249-a022264eb531.png)

这是xml的逻辑

**Comment by HuangLK** [comment]
有两个点需要注意下：
1. 流程图中的`INTENT_START_UP`应该改成Unit上的意图名`START_UP`；
2. 给流程图补充上回复的节点

**Comment by syschen** [comment]
![image](https://user-images.githubusercontent.com/8849212/64413631-6e0ca280-d0c4-11e9-9bf2-96055bcc82d9.png)
我就想先实现个简单的一问一答，把流程跑通
这样意图改了，但是转json是空的了
![image](https://user-images.githubusercontent.com/8849212/64413724-9c8a7d80-d0c4-11e9-947a-52c1b03ded92.png)

**Comment by HuangLK** [comment]
前段时候drawio更新之后导出的xml多了两层结构，生成配置的工具还没升级，需要做一些手动调整，比如：
```
<?xml version="1.0" encoding="UTF-8"?>
<mxfile modified="2019-07-28T12:00:13.837Z" host="www.draw.io" agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36" version="11.0.7" etag="ZDDlISiZOqnBBiCkCztp" type="device" compressed="false">
  <diagram id="3g8qPibVMTihKgiJrXBh" name="Page-1">
    <mxGraphModel dx="1796" dy="593" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="850" pageHeight="1100" background="#ffffff" math="0" shadow="0">
      <root>
	...
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
```
只需要把`mxGraphModel`和`diagram`这两层删掉，DMKit的图形化工具即可正常使用。
```
<?xml version="1.0" encoding="UTF-8"?>
<mxfile modified="2019-07-28T12:00:13.837Z" host="www.draw.io" agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36" version="11.0.7" etag="ZDDlISiZOqnBBiCkCztp" type="device" compressed="false">
      <root>
	...
      </root>
</mxfile>
```
可以检查下是不是这个问题

**Comment by syschen** [comment]
![image](https://user-images.githubusercontent.com/8849212/64417417-9d72dd80-d0cb-11e9-977d-e429131c7063.png)
这个我知道  已经去掉了外层的
run.py也没有报错

**Comment by syschen** [comment]
![image](https://user-images.githubusercontent.com/8849212/64418441-9947bf80-d0cd-11e9-8c2f-1cd2c1e9aeda.png)

还有这个问题，有时也会遇到，看提示好像是哪里的箭头不对，是xml哪里有问题吗？
![image](https://user-images.githubusercontent.com/8849212/64418547-cb592180-d0cd-11e9-8413-ca332caa30d2.png)

这是完整的xml，还没有删去外面两层
<?xml version="1.0" encoding="UTF-8"?>
    <mxGraphModel dx="1666" dy="747" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169" math="0" shadow="0">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
        <mxCell id="2" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;exitX=0.5;exitY=1;entryX=0.5;entryY=0;jettySize=auto;orthogonalLoop=1;strokeWidth=2;" edge="1" target="5" parent="1">
          <mxGeometry relative="1" as="geometry">
            <mxPoint x="710" y="160" as="sourcePoint"/>
          </mxGeometry>
        </mxCell>
        <mxCell id="3" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=0;exitY=0.5;exitDx=0;exitDy=0;entryX=1;entryY=0.5;entryDx=0;entryDy=0;" edge="1" source="5" target="8" parent="1">
          <mxGeometry relative="1" as="geometry"/>
        </mxCell>
        <mxCell id="4" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;" edge="1" source="5" target="10" parent="1">
          <mxGeometry relative="1" as="geometry"/>
        </mxCell>
        <mxCell id="5" value="BOT:您好，有什么可以帮您？&lt;span&gt;&lt;br&gt;&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;" vertex="1" parent="1">
          <mxGeometry x="580" y="230" width="260" height="60" as="geometry"/>
        </mxCell>
        <mxCell id="6" value="INTENT:START_UP&lt;br&gt;SLOT:user_hello" style="ellipse;whiteSpace=wrap;html=1;" vertex="1" parent="1">
          <mxGeometry x="580" y="80" width="260" height="80" as="geometry"/>
        </mxCell>
        <mxCell id="7" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;" edge="1" source="8" parent="1">
          <mxGeometry relative="1" as="geometry">
            <mxPoint x="340" y="380" as="targetPoint"/>
          </mxGeometry>
        </mxCell>
        <mxCell id="8" value="INTENT:INTENT_YES&lt;br&gt;SLOT:user_yes" style="ellipse;whiteSpace=wrap;html=1;" vertex="1" parent="1">
          <mxGeometry x="210" y="220" width="260" height="80" as="geometry"/>
        </mxCell>
        <mxCell id="9" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;" edge="1" source="10" parent="1">
          <mxGeometry relative="1" as="geometry">
            <mxPoint x="1060" y="380" as="targetPoint"/>
          </mxGeometry>
        </mxCell>
        <mxCell id="10" value="INTENT:INTENT_NO&lt;br&gt;SLOT:user_no" style="ellipse;whiteSpace=wrap;html=1;" vertex="1" parent="1">
          <mxGeometry x="930" y="220" width="260" height="80" as="geometry"/>
        </mxCell>
        <mxCell id="11" value="" style="rounded=1;whiteSpace=wrap;html=1;" vertex="1" parent="1">
          <mxGeometry x="210" y="380" width="260" height="110" as="geometry"/>
        </mxCell>
        <mxCell id="12" value="" style="rounded=1;whiteSpace=wrap;html=1;" vertex="1" parent="1">
          <mxGeometry x="875" y="370" width="370" height="110" as="geometry"/>
        </mxCell>
        <mxCell id="13" value="BOT:好的，马上为您服务" style="text;html=1;" vertex="1" parent="1">
          <mxGeometry x="260" y="415" width="180" height="30" as="geometry"/>
        </mxCell>
        <mxCell id="14" value="BOT:好的，希望下次能为您服务，再见。" style="text;html=1;" vertex="1" parent="1">
          <mxGeometry x="980" y="405" width="180" height="30" as="geometry"/>
        </mxCell>
      </root>
    </mxGraphModel>

**Comment by HuangLK** [comment]
右边的连线没有箭头

**Comment by syschen** [comment]
![image](https://user-images.githubusercontent.com/8849212/64505651-2cb80500-d307-11e9-9243-df0d8ccc00ef.png)
这个呢   这个可以转json  但是又resolve failed了
![image](https://user-images.githubusercontent.com/8849212/64505679-48bba680-d307-11e9-9a37-a6259088ef7d.png)

policy也贴下吧
[
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "请问有什么可以帮您？"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "001"
        }
      }
    ], 
    "params": [], 
    "trigger": {
      "intent": "START_UP", 
      "slots": [
        "user_hello"
      ], 
      "state": ""
    }
  }, 
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "请确认：血压{%bp%},血糖{%bs%}"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "002"
        }
      }
    ], 
    "params": [
      {
        "name": "bp", 
        "type": "slot_val", 
        "value": "user_blood_pressure"
      }, 
      {
        "name": "bs", 
        "type": "slot_val", 
        "value": "user_blood_sugar"
      }
    ], 
    "trigger": {
      "intent": "", 
      "slots": [
        "user_blood_pressure", 
        "user_blood_sugar"
      ], 
      "state": "001"
    }
  }, 
  {
    "output": [
      {
        "assertion": [], 
        "result": [
          {
            "type": "tts", 
            "value": "正在为您查询。。。"
          }
        ], 
        "session": {
          "context": {}, 
          "state": "003"
        }
      }
    ], 
    "params": [
      {
        "name": "bp", 
        "type": "slot_val", 
        "value": "user_blood_pressure"
      }, 
      {
        "name": "bs", 
        "type": "slot_val", 
        "value": "user_blood_sugar"
      }, 
      {
        "name": "analysis_option", 
        "type": "func_val", 
        "value": "service_http_get:analysis_service,/data/analysis?bp={%bp%}&bs={%bs%}"
      }
    ], 
    "trigger": {
      "intent": "INTENT_YES", 
      "slots": [], 
      "state": "002"
    }
  }
]

![image](https://user-images.githubusercontent.com/8849212/64505744-86b8ca80-d307-11e9-8152-1e166edc95a3.png)
UNIT平台上应该是命中意图了吧

**Comment by HuangLK** [comment]
你的policy里`trigger`需要意图和词槽同时满足条件才算命中，看UNIT平台的截图只有意图没有词槽，可以考虑把policy里`trigger`的词槽设为[]
