### ISSUE TITLE
客户端访问返回"error_code":282008问题

### ISSUE THREAD

**Issue by xyl70** [baidu/unit-dmkit#87]
客户端访问出现"error_code":282008问题，没找到原因。
用示例代码/unit-dmkit/tools/bot_emulator.py 服务正常，访问做格式是
input:
是的
{"version": "2.0", "bot_id": "47230", "log_id": "345521", "request": {"user_id": "48876", "query": "\u662f\u7684", "query_info": {"type": "TEXT", "source": "ASR", "asr_candidates": []}, "updates": "", "client_session": "{\"client_results\":\"\", \"candidate_options\":[], \"client_name\":\"\u5f20\u4e09\"}", "bernard_level": 1}, "bot_session": ""}
BOT:
请问你的收货地址是广州市白云区三元里大道北(张三)，对吗？
-----------------------------------------------------------------
这段服务正常。

用示例代码 https://ai.baidu.com/docs#/UNIT-v2-API/41351cb4（C++)访问返回"error_code":282008，访问做格式是
{"version": "2.0", "bot_id": "47230", "log_id": "419856", "request": {"user_id": "98383", "query": "是的", "query_info": {"type": "TEXT", "source": "ASR", "asr_candidates": []}, "updates": "", "client_session": {"client_results":"", "candidate_options":[], "client_name":"张三"}, "bernard_level": 1}, "bot_session": ""}
result:{"error_code":282008,"error_msg":"The request content type is illegal."}

C++代码：
std::cout << "请输入客户名字: ";
    std::cin >> name;
    std::cout << name << std::endl;
    std::cout << "BOT:你好！我是王卡专员，请问你是" << name << "吗？" << std::endl;
    query = "是的";
    std::string json_request_body = "{\"version\": \"2.0\", \"bot_id\": \"47230\", \"log_id\": \"419856\", \"request\": {\"user_id\": \"98383\", \"query\": \"\u662f\u7684\", \"query_info\": {\"type\": \"TEXT\", \"source\": \"ASR\", \"asr_candidates\": []}, \"updates\": \"\", \"client_session\": {\"client_results\":\"\", \"candidate_options\":[], \"client_name\":\"\u5f20\u4e09\"}, \"bernard_level\": 1}, \"bot_session\": \"\"}";
    std::cout << "json_request_body:" << json_request_body << std::endl;
    unit_utterance(result,  json_request_body, access_token) ;
访问格式相同，但返回结果C++错误，查了很久，没发现json结构有问题。

dmkit显示是：
C++请求错误的内容：
I0910 09:14:11.889983  5619 /home/xie/unit-dmkit/src/dialog_manager.cpp:64] logid= received request: {"version": "2.0", "bot_id": "47230", "log_id": "419856", "request": {"user_id": "98383", "query": "是的", "query_info": {"type": "TEXT", "source": "ASR", "asr_candidates": []}, "updates": "", "client_session": {"client_results":"", "candidate_options":[], "client_name":"张三"}, "bernard_level": 1}, "bot_session": ""}
I0910 09:14:11.890047  5619 /home/xie/unit-dmkit/src/dialog_manager.cpp:132] logid=dmkit_419856 dm session: 
I0910 09:14:11.890087  5619 /home/xie/unit-dmkit/src/dialog_manager.cpp:295] logid=dmkit_419856 Calling unit bot service, url: /rpc/2.0/unit/bot/chat?access_token=24.e9b65c6dfd16cd6fec8a9bfc454ce709.2592000.1570670041.282335-16149815
I0910 09:14:11.890113  5619 /home/xie/unit-dmkit/src/dialog_manager.cpp:296] logid=dmkit_419856 {"version":"2.0","bot_id":"47230","log_id":"dmkit_419856","request":{"user_id":"98383","query":"是的","query_info":{"type":"TEXT","source":"ASR","asr_candidates":[]},"updates":"","client_session":{"client_results":"","candidate_options":[],"client_name":"张三"},"bernard_level":1},"bot_session":""}
I0910 09:14:11.890150  5619 /home/xie/unit-dmkit/src/remote_service_manager.cpp:112] logid=dmkit_419856 Calling service unit_bot
I0910 09:14:12.077461  5617 /home/xie/unit-dmkit/src/remote_service_manager.cpp:152] logid=dmkit_419856 remote_side=14.215.178.97:443, cost=187
I0910 09:14:12.077521  5617 /home/xie/unit-dmkit/src/dialog_manager.cpp:302] logid=dmkit_419856 Got unit bot result
I0910 09:14:12.077542  5617 /home/xie/unit-dmkit/src/dialog_manager.cpp:185] logid=dmkit_419856 unit bot result: {"error_code":282008,"error_msg":"The request content type is illegal."}
I0910 09:14:12.077637  5617 /home/xie/unit-dmkit/src/app_container.cpp:97] logid=dmkit_419856 Application run cost(ms): 187.695
N0910 09:14:12.077683  5617 /home/xie/unit-dmkit/src/app_container.cpp:99] logid=dmkit_419856 req={"version": "2.0", "bot_id": "47230", "log_id": "419856", "request": {"user_id": "98383", "query": "是的", "query_info": {"type": "TEXT", "source": "ASR", "asr_candidates": []}, "updates": "", "client_session": {"client_results":"", "candidate_options":[], "client_name":"张三"}, "bernard_level": 1}, "bot_session": ""} service_unit_bot=remote:14.215.178.97:443|tm:187|ret:0 ret={"error_code":282008,"error_msg":"The request content type is illegal."} tm=187.695412 

python请求正确的内容：
I0910 10:28:50.738177  5619 /home/xie/unit-dmkit/src/dialog_manager.cpp:64] logid= received request: {"version": "2.0", "bot_id": "47230", "log_id": "345521", "request": {"user_id": "48876", "query": "\u662f\u7684", "query_info": {"type": "TEXT", "source": "ASR", "asr_candidates": []}, "updates": "", "client_session": "{\"client_results\":\"\", \"candidate_options\":[], \"client_name\":\"\u5f20\u4e09\"}", "bernard_level": 1}, "bot_session": ""}
I0910 10:28:50.738224  5619 /home/xie/unit-dmkit/src/dialog_manager.cpp:132] logid=dmkit_345521 dm session: 
I0910 10:28:50.738264  5619 /home/xie/unit-dmkit/src/dialog_manager.cpp:295] logid=dmkit_345521 Calling unit bot service, url: /rpc/2.0/unit/bot/chat?access_token=24.b6e7cf5440ca4e2bd941e07c232bca41.2592000.1570674506.282335-16149815
I0910 10:28:50.738343  5619 /home/xie/unit-dmkit/src/dialog_manager.cpp:296] logid=dmkit_345521 {"version":"2.0","bot_id":"47230","log_id":"dmkit_345521","request":{"user_id":"48876","query":"是的","query_info":{"type":"TEXT","source":"ASR","asr_candidates":[]},"updates":"","client_session":"{\"client_results\":\"\", \"candidate_options\":[], \"client_name\":\"张三\"}","bernard_level":1},"bot_session":""}
I0910 10:28:50.738366  5619 /home/xie/unit-dmkit/src/remote_service_manager.cpp:112] logid=dmkit_345521 Calling service unit_bot
I0910 10:28:51.296084  5619 /home/xie/unit-dmkit/src/remote_service_manager.cpp:152] logid=dmkit_345521 remote_side=14.215.178.97:443, cost=557
I0910 10:28:51.296139  5619 /home/xie/unit-dmkit/src/dialog_manager.cpp:302] logid=dmkit_345521 Got unit bot result
I0910 10:28:51.296360  5619 /home/xie/unit-dmkit/src/dialog_manager.cpp:185] logid=dmkit_345521 unit bot result: {"result":{"version":"2.0","timestamp":"2019-09-10 10:28:51.071","response":{"msg":"ok","schema":{"intent_confidence":100.0,"slots":[],"domain_confidence":0.0,"slu_tags":[],"intent":"INTENT_YES"},"qu_res":{"candidates":[{"intent_confidence":100.0,"match_info":"{\"group_id\":\"4\",\"id\":\"1147902\",\"informal_word\":\"是\\t的\",\"match_keywords\":\" kw_yes:是的\",\"match_pattern\":\"[W:0-2][D:kw_yes][W:0-4]\",\"ori_pattern\":\"[W:0-2]
......

**Comment by xyl70** [comment]
c++ 代码原来用json定义转字符串，我为了简化测试，直接字符串定义，转义是正确的，网页不显示转义符

**Comment by xyl70** [comment]
问题出在这里去掉"client_session": "{"client_results":"", "candidate_options":[], "client_name":"\u5f20\u4e09"}",就正常了,不知这个格式什么问题
![error](https://user-images.githubusercontent.com/34577341/64662701-e59f5080-d47b-11e9-96bb-ab8fc64f53ec.png)
![ok](https://user-images.githubusercontent.com/34577341/64662711-ecc65e80-d47b-11e9-9811-2a6f2e91ac55.png)

**Comment by HuangLK** [comment]
```
"client_session": "{"client_results":"", "candidate_options":[], "client_name":"\u5f20\u4e09"}"
```
值是字符串类型，需要做转义操作，正确的形式应该是：
```
"client_session": "{\"client_results\":\"\", \"candidate_options\":[], \"client_name\": \"张三\"}"
```

**Comment by xyl70** [comment]
python的json定义：
![pycode](https://user-images.githubusercontent.com/34577341/64664584-2b5f1780-d482-11e9-84b3-355e70b05b66.png)
c++的json定义：
![cppcode](https://user-images.githubusercontent.com/34577341/64664617-45005f00-d482-11e9-9888-5f629d8ae80c.png)
这个定义有差别吗？

**Comment by HuangLK** [comment]
c++代码里需要先单独构建client_session这个json对象，**然后做一步json_to_str的操作转成字符串**，再赋值给request["client_session"]。

**Comment by xyl70** [comment]
可以了，是差这步转换成字符串再赋值
