### ISSUE TITLE
bot_emulator.py回应DM policy resolve failed

### ISSUE THREAD

**Issue by urcllr** [baidu/unit-dmkit#9]
运行bot_emulator.py界面：
![a](https://user-images.githubusercontent.com/38638662/43513022-4adeb72c-95af-11e8-9546-c16069fa6307.png)

dmkit服务输出：
![a](https://user-images.githubusercontent.com/38638662/43513130-89dc17b2-95af-11e8-901f-68b8ceac815e.png)

**Comment by jiyoushengbd** [comment]
请检查conf/app/products.json中是否设置了正确的botid。编译时配置文件会被复制到_build目录下，程序执行时将加载_build目录下对应的配置文件。

**Comment by kongkongthu** [comment]
到底是设置botid还是技能id？应该是技能id吧？
